import '../procedure_model.dart';

const ProceduresData ctProcedures = ProceduresData(
  deviceId: 'ct',
  intro:
      'CT هو أكثر جهاز له أنواع فحوصات. تتنوع بين تشخيصي، تداخلي، ووظيفي. '
      'نذكر هنا الأكثر استخداماً في الممارسة اليومية.',
  procedures: [
    Procedure(
      id: 'ct_head_plain',
      icon: '🧠',
      nameEn: 'CT Head (Non-contrast)',
      nameAr: 'CT دماغ بدون تباين',
      shortDesc:
          'الفحص الأول للطوارئ الدماغية — نزيف، جلطة، إصابات الرأس. سريع جداً.',
      type: ProcedureType.diagnostic,
      duration: '5 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة (2 mSv)',
      indications: [
        'نزيف دماغي حاد',
        'جلطة دماغية',
        'إصابة الرأس (Trauma)',
        'صداع مفاجئ شديد',
        'فقدان وعي',
        'تقييم بعد العمليات',
      ],
      preparationSteps: [
        'خلع المجوهرات ودبابيس الشعر',
        'الاستلقاء على الظهر',
        'تثبيت الرأس بلطف',
        'البقاء ساكناً تماماً',
      ],
      notes: 'الفحص المفضل في الطوارئ — النتيجة في دقيقتين.',
    ),
    Procedure(
      id: 'ct_head_contrast',
      icon: '🧠',
      nameEn: 'CT Head (With Contrast)',
      nameAr: 'CT دماغ مع تباين',
      shortDesc:
          'CT دماغ مع تباين وريدي. يُظهر الأورام، الالتهابات، والأوعية.',
      type: ProcedureType.diagnostic,
      duration: '10 دقائق',
      preparation: 'صيام 4 ساعات',
      contrast: 'وريدي (يودي)',
      doseLevel: 'متوسطة (4 mSv)',
      indications: [
        'أورام دماغية',
        'خراج دماغي',
        'التهاب سحايا',
        'نقائل دماغية',
        'تقييم بعد الجراحة',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'قياس الكرياتينين',
        'إيقاف Metformin 48 ساعة',
        'تركيب كانيولا وريدية',
        'السؤال عن الحساسية',
      ],
      notes: 'التباين يُظهر الأوعية والأورام بوضوح أكبر.',
    ),
    Procedure(
      id: 'ct_chest',
      icon: '🫁',
      nameEn: 'CT Chest',
      nameAr: 'CT صدر',
      shortDesc:
          'CT للصدر — الرئة، المنصف، الأضلاع. دقة أعلى من X-ray بكثير.',
      type: ProcedureType.diagnostic,
      duration: '10 دقائق',
      preparation: 'صيام 4 ساعات',
      contrast: 'وريدي (غالباً)',
      doseLevel: 'متوسطة (7 mSv)',
      indications: [
        'أورام الرئة',
        'عقد لمفية منصفية',
        'استرواح صدر معقد',
        'أمراض الرئة الخلالية',
        'تقييم انتشار النقائل',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'قياس الكرياتينين (للتباين)',
        'خلع المعادن من الصدر',
        'رفع الذراعين فوق الرأس',
        'حبس النفس عند الطلب',
      ],
      notes: 'HRCT (High-Resolution) بدقة أعلى لأمراض الرئة الخلالية.',
    ),
    Procedure(
      id: 'hrct',
      icon: '🔬',
      nameEn: 'HRCT (High-Resolution CT)',
      nameAr: 'CT صدر عالي الدقة',
      shortDesc:
          'شرائح رقيقة جداً (1 mm) لدراسة أنسجة الرئة بتفاصيل دقيقة.',
      type: ProcedureType.diagnostic,
      duration: '10 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'متوسطة (3 mSv)',
      indications: [
        'التليف الرئوي',
        'الالتهاب الرئوي الخلالي',
        'الساركويد',
        'توسع القصبات',
        'أمراض الرئة المهنية',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'الاستلقاء على الظهر',
        'رفع الذراعين فوق الرأس',
        'حبس النفس بعمق',
      ],
      notes: 'شرائح 1 mm بدلاً من 5-10 mm. تُظهر تفاصيل لا تُرى في CT العادي.',
    ),
    Procedure(
      id: 'ct_abdomen',
      icon: '🩻',
      nameEn: 'CT Abdomen (With Contrast)',
      nameAr: 'CT بطن مع تباين',
      shortDesc:
          'CT للبطن — الكبد، الكلى، البنكرياس، الأمعاء. مع تباين فموي ووريدي.',
      type: ProcedureType.diagnostic,
      duration: '15-20 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'فموي + وريدي',
      doseLevel: 'متوسطة (10 mSv)',
      indications: [
        'أورام الكبد والكلى',
        'التهاب البنكرياس',
        'انسداد معوي',
        'التهاب الزائدة',
        'خراج بطني',
        'إصابات البطن',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'شرب التباين الفموي قبل 45-60 دقيقة',
        'قياس الكرياتينين',
        'تركيب كانيولا وريدية',
        'حبس النفس متكرر',
      ],
      notes: 'التباين الفموي يُظهر الأمعاء، الوريدي يُظهر الأعضاء.',
    ),
    Procedure(
      id: 'ct_kub',
      icon: '🫘',
      nameEn: 'CT KUB',
      nameAr: 'CT الكلى والحالب والمثانة',
      shortDesc:
          'CT بدون تباين لحصى الكلى. الأسرع والأدق لكشف الحصى.',
      type: ProcedureType.diagnostic,
      duration: '5-10 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'متوسطة (5 mSv)',
      indications: [
        'حصى الكلى والحالب',
        'ألم خاصرة حاد',
        'دم في البول',
        'انسداد بولي',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'الاستلقاء على الظهر',
        'تفريغ المثانة قبل الفحص',
        'حبس النفس مرة واحدة',
      ],
      notes: 'Low-Dose CT KUB يقلل الجرعة إلى 1-2 mSv مع دقة عالية.',
    ),
    Procedure(
      id: 'cta',
      icon: '🩸',
      nameEn: 'CT Angiography (CTA)',
      nameAr: 'تصوير الأوعية بالـ CT',
      shortDesc:
          'CT مع تباين وريدي لعرض الشرايين بدقة عالية. بديل أقل توغلاً من القسطرة.',
      type: ProcedureType.interventional,
      duration: '15 دقيقة',
      preparation: 'صيام 4-6 ساعات',
      contrast: 'وريدي (يودي)',
      doseLevel: 'متوسطة-عالية (10-15 mSv)',
      indications: [
        'تضيّق الشرايين',
        'أم الدم (Aneurysm)',
        'جلطة رئوية (CTPA)',
        'تسلّخ الأبهر (Dissection)',
        'تقييم قبل الجراحة',
      ],
      preparationSteps: [
        'صيام 4-6 ساعات',
        'قياس الكرياتينين (إلزامي)',
        'إيقاف Metformin 48 ساعة',
        'كانيولا كبيرة (18 G)',
        'Bolus Tracking',
      ],
      notes: 'CTPA هو الفحص المفضل للجلطة الرئوية — أدق من V/Q Scan.',
    ),
    Procedure(
      id: 'ct_colonography',
      icon: '🫃',
      nameEn: 'CT Colonography',
      nameAr: 'CT القولون (تنظير افتراضي)',
      shortDesc:
          'تنظير قولون افتراضي بالـ CT بدون منظار. أقل توغلاً من التنظير العادي.',
      type: ProcedureType.diagnostic,
      duration: '20 دقيقة',
      preparation: 'تحضير قولون كامل',
      contrast: 'فموي + وريدي',
      doseLevel: 'متوسطة (10 mSv)',
      indications: [
        'فحص سرطان القولون',
        'متابعة بعد استئصال الورم',
        'مرضى غير قادرين على التنظير',
        'انسداد قولوني',
      ],
      preparationSteps: [
        'تحضير قولون كامل (محلول خاص)',
        'صيام ليلة كاملة',
        'نفخ القولون بثاني أكسيد الكربون',
        'تصوير في وضعيتين (Supine, Prone)',
      ],
      notes: 'لا يُغني عن التنظير — الخزعة تحتاج منظار.',
    ),
    Procedure(
      id: 'ct_perfusion',
      icon: '📊',
      nameEn: 'CT Perfusion',
      nameAr: 'CT تروية الدماغ',
      shortDesc:
          'يقيس تدفق الدم في الدماغ. أساسي لتحديد الجلطة القابلة للعلاج.',
      type: ProcedureType.functional,
      duration: '20 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'وريدي',
      doseLevel: 'متوسطة-عالية',
      indications: [
        'جلطة دماغية حادة',
        'تحديد المنطقة القابلة للإنقاذ',
        'تقييم بعد الجلطة',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'تركيب كانيولا وريدية كبيرة',
        'حقن سريع (5 mL/s)',
        'مراقبة دقيقة للمريض',
      ],
      notes: 'يُجرى مع CT دماغ و CTA — "بروتوكول الجلطة" الشامل.',
    ),
    Procedure(
      id: 'ct_low_dose_lung',
      icon: '🫁',
      nameEn: 'Low-Dose CT Lung Screening',
      nameAr: 'CT منخفض الجرعة للرئة',
      shortDesc:
          'فحص دوري للمدخنين لاكتشاف سرطان الرئة المبكر. جرعة منخفضة جداً.',
      type: ProcedureType.diagnostic,
      duration: '5 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة (1.5 mSv)',
      indications: [
        'مدخنون 50-80 سنة',
        'تاريخ تدخين ≥ 20 علبة-سنة',
        'مدخنون حاليون أو أقل من 15 سنة من الإقلاع',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'الاستلقاء على الظهر',
        'رفع الذراعين فوق الرأس',
        'حبس النفس',
      ],
      notes: 'يُقلل وفيات سرطان الرئة بنسبة 20%. يُكرر سنوياً.',
    ),
    Procedure(
      id: 'dext',
      icon: '⚡',
      nameEn: 'Dual-Energy CT (DECT)',
      nameAr: 'CT ثنائي الطاقة',
      shortDesc:
          'CT بمنظومتين طاقيتين في نفس الوقت. يُظهر تكوين الحصى والأنسجة.',
      type: ProcedureType.functional,
      duration: '10 دقائق',
      preparation: 'حسب الفحص',
      contrast: 'حسب الفحص',
      doseLevel: 'متوسطة',
      indications: [
        'تحليل تكوين حصى الكلى',
        'النقرس (Gout)',
        'الأورام',
        'الأوعية الدموية',
        'تقييم العظام',
      ],
      preparationSteps: [
        'حسب نوع الفحص',
        'بدون تحضير خاص عادة',
      ],
      notes: 'تقنية حديثة — تحدد تكوين الحصى بدون تحليل مخبري.',
    ),
    Procedure(
      id: 'ct_guided',
      icon: '💉',
      nameEn: 'CT-Guided Biopsy / Drainage',
      nameAr: 'خزعة / تصريف موجه بالـ CT',
      shortDesc:
          'إجراء تداخلي — خزعة أو تصريف خراج بمساعدة CT الحية.',
      type: ProcedureType.interventional,
      duration: '30-60 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'حسب الحالة',
      doseLevel: 'متوسطة-عالية',
      indications: [
        'أورام غير معروفة التشخيص',
        'خراج بطني',
        'تجمع سائل',
        'عينة من الرئة أو الكبد',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل التخثر',
        'توقيع موافقة',
        'تخدير موضعي',
        'مراقبة بعد الإجراء',
      ],
      notes: 'الطبيب الأشعة يستخدم CT الحية لتوجيه الإبرة بدقة.',
    ),
  ],
  comparisonHeaders: ['الفحص', 'المدة', 'الجرعة', 'الأفضل لـ'],
  comparisonTable: [
    ['دماغ بدون تباين', '5 دقائق', '2 mSv', 'الطوارئ والنزيف'],
    ['دماغ مع تباين', '10 دقائق', '4 mSv', 'الأورام والالتهابات'],
    ['صدر', '10 دقائق', '7 mSv', 'الأورام والعقد'],
    ['HRCT', '10 دقائق', '3 mSv', 'أمراض الرئة الخلالية'],
    ['بطن', '15-20 دقيقة', '10 mSv', 'الأورام والالتهابات'],
    ['KUB', '5-10 دقائق', '5 mSv', 'حصى الكلى'],
    ['CTA', '15 دقيقة', '10-15 mSv', 'الشرايين والجلطات'],
    ['Colonography', '20 دقيقة', '10 mSv', 'سرطان القولون'],
    ['Perfusion', '20 دقيقة', 'متوسطة-عالية', 'الجلطة الدماغية'],
    ['Low-Dose Lung', '5 دقائق', '1.5 mSv', 'فحص المدخنين'],
  ],
);