import '../procedure_model.dart';

const ProceduresData fluoroscopyProcedures = ProceduresData(
  deviceId: 'fluoro',
  intro:
      'Fluoroscopy يُستخدم في إجراءات كثيرة — من بسيطة (بلع الباريوم) إلى '
      'معقدة (قسطرة القلب). الجرعة قد تكون عالية، والالتزام بالحماية إلزامي.',
  procedures: [
    Procedure(
      id: 'barium_swallow',
      icon: '🥤',
      nameEn: 'Barium Swallow',
      nameAr: 'بلع الباريوم',
      shortDesc:
          'تصوير المريء والبلع بتباين فموي (باريوم). بسيط وسريع.',
      type: ProcedureType.diagnostic,
      duration: '15-20 دقيقة',
      preparation: 'صيام 6-8 ساعات',
      contrast: 'باريوم فموي',
      doseLevel: 'منخفضة (1-3 mSv)',
      indications: [
        'صعوبة البلع (Dysphagia)',
        'الارتجاع',
        'تشوهات المريء',
        'بعد العمليات',
      ],
      preparationSteps: [
        'صيام من الليل',
        'عدم التدخين صباحاً',
        'شرب الباريوم',
        'تصوير أثناء البلع',
      ],
      notes: 'بسيط — 15 دقيقة. لا يُستخدم في الانسداد الكامل.',
    ),
    Procedure(
      id: 'barium_meal',
      icon: '🍽️',
      nameEn: 'Barium Meal (UGI)',
      nameAr: 'بلع الباريوم للمعدة',
      shortDesc:
          'تصوير المعدة والاثني عشر بالباريوم.',
      type: ProcedureType.diagnostic,
      duration: '30-45 دقيقة',
      preparation: 'صيام 8 ساعات',
      contrast: 'باريوم فموي',
      doseLevel: 'منخفضة-متوسطة (3-5 mSv)',
      indications: [
        'قرحة المعدة',
        'أورام المعدة',
        'التهاب المعدة',
        'انسداد مخرج المعدة',
      ],
      preparationSteps: [
        'صيام 8 ساعات',
        'شرب باريوم + فوار (Gas)',
        'تصوير في وضعيات مختلفة',
        'الضغط على المعدة أحياناً',
      ],
      notes: 'أقل استخداماً بعد CT — لكنه مفيد للحركة.',
    ),
    Procedure(
      id: 'barium_enema',
      icon: '💧',
      nameEn: 'Barium Enema',
      nameAr: 'حقنة الباريوم الشرجية',
      shortDesc:
          'تصوير القولون بتباين شرجي. لكشف الأورام والالتهابات.',
      type: ProcedureType.diagnostic,
      duration: '30-45 دقيقة',
      preparation: 'تحضير قولون كامل',
      contrast: 'باريوم شرجي + هواء (Double Contrast)',
      doseLevel: 'متوسطة (5-8 mSv)',
      indications: [
        'أورام القولون',
        'التهاب القولون',
        'داء الرتوج',
        'انسداد قولوني',
      ],
      preparationSteps: [
        'صيام ليلة كاملة',
        'محلول تحضير قولون',
        'حقنة شرجية بالباريوم',
        'نفخ هواء',
        'تصوير في وضعيات متعددة',
      ],
      notes: 'أقل استخداماً بعد CT Colonography.',
    ),
    Procedure(
      id: 'ivp',
      icon: '🫘',
      nameEn: 'IVP (Intravenous Pyelogram)',
      nameAr: 'تصوير الجهاز البولي',
      shortDesc:
          'تصوير الكلى والحالب والمثانة بتباين وريدي.',
      type: ProcedureType.diagnostic,
      duration: '30-60 دقيقة',
      preparation: 'صيام + تحضير قولون',
      contrast: 'وريدي (يودي)',
      doseLevel: 'متوسطة (5-7 mSv)',
      indications: [
        'حصى الكلى',
        'أورام الجهاز البولي',
        'تشوهات خلقية',
        'انسداد بولي',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'تحضير قولون بسيط',
        'قياس الكرياتينين',
        'حقن تباين وريدي',
        'تصوير متسلسل',
      ],
      notes: 'شبه استُبدل بـ CT Urography.',
    ),
    Procedure(
      id: 'cardiac_cath',
      icon: '❤️',
      nameEn: 'Cardiac Catheterization',
      nameAr: 'قسطرة القلب',
      shortDesc:
          'تصوير الشرايين التاجية بتباين + إمكانية رأب الأوعية.',
      type: ProcedureType.interventional,
      duration: '30-60 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'وريدي (يودي)',
      doseLevel: 'عالية (5-15 mSv)',
      indications: [
        'ألم صدري',
        'جلطة قلبية',
        'تضيّق الشرايين',
        'تقييم قبل الجراحة',
        'رأب الأوعية',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'قياس الكرياتينين',
        'حلاقة موضع البزل (الفخذ/الرسغ)',
        'تخدير موضعي',
        'قسطرة + تباين',
      ],
      notes: 'قد يتحول إلى رأب فوري (Angioplasty + Stent).',
    ),
    Procedure(
      id: 'angioplasty',
      icon: '🩸',
      nameEn: 'Angioplasty + Stenting',
      nameAr: 'رأب الأوعية والدعامات',
      shortDesc:
          'توسيع الشرايين المتضيقة بالبالون + زرع دعامة.',
      type: ProcedureType.interventional,
      duration: '45-90 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'وريدي (يودي)',
      doseLevel: 'عالية (10-30 mSv)',
      indications: [
        'تضيّق الشرايين التاجية',
        'تضيّق الشرايين الطرفية',
        'تضيّق الشرايين الكلوية',
        'تضيّق السباتي',
      ],
      preparationSteps: [
        'قياس الكرياتينين',
        'مضادات صفائح قبل',
        'تخدير موضعي',
        'قسطرة + بالون',
        'زرع دعامة (Drug-Eluting)',
        'مراقبة 4-6 ساعات',
      ],
      notes: 'قد يكون بديلاً للجراحة المفتوحة.',
    ),
    Procedure(
      id: 'tace',
      icon: '🎗️',
      nameEn: 'TACE (Liver)',
      nameAr: 'علاج كيميائي موضعي للكبد',
      shortDesc:
          'حقن دواء كيميائي + إغلاق الأوعية المغذية للورم.',
      type: ProcedureType.interventional,
      duration: '60-90 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'يودي + دواء كيميائي',
      doseLevel: 'عالية',
      indications: [
        'سرطان الكبد (HCC)',
        'نقائل كبدية',
        'أورام غير قابلة للاستئصال',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل شاملة',
        'تخدير موضعي',
        'قسطرة الشريان الكبدي',
        'حقن الدواء + إغلاق الأوعية',
      ],
      notes: 'يُطيل الحياة في سرطان الكبد المتقدم.',
    ),
    Procedure(
      id: 'tips',
      icon: '🩸',
      nameEn: 'TIPS',
      nameAr: 'تحويلة داخلية كبدية',
      shortDesc:
          'إنشاء تحويلة بين الوريد البابي والوريد الكبدي.',
      type: ProcedureType.interventional,
      duration: '90-120 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'يودي + دعامة',
      doseLevel: 'عالية',
      indications: [
        'نزيف دوالي المريء',
        'استسقاء بطني مقاوم',
        'متلازمة بود كياري',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل شاملة',
        'تخدير موضعي + مهدئ',
        'قسطرة الوريد الوداجي',
        'إنشاء التحويلة',
      ],
      notes: 'إجراء معقد — يحتاج خبرة عالية.',
    ),
    Procedure(
      id: 'embolization',
      icon: '💉',
      nameEn: 'Embolization',
      nameAr: 'إغلاق الأوعية',
      shortDesc:
          'إغلاق أوعية دموية علاجياً — أورام، نزيف، أورام ليفية.',
      type: ProcedureType.interventional,
      duration: '60-120 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'يودي + مواد إغلاق',
      doseLevel: 'عالية',
      indications: [
        'نزيف حاد',
        'أورام ليفية رحمية',
        'أورام الكبد',
        'أم الدم',
        'دوالي الخصية',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل',
        'تخدير موضعي',
        'قسطرة الوعاء',
        'حقن مواد الإغلاق',
        'مراقبة بعد',
      ],
      notes: 'UAE للأورام الليفية بديل للاستئصال.',
    ),
    Procedure(
      id: 'vertebroplasty',
      icon: '🦴',
      nameEn: 'Vertebroplasty / Kyphoplasty',
      nameAr: 'تثبيت الفقرات بالأسمنت',
      shortDesc:
          'حقن أسمنت عظمي في فقرة مكسورة لتسكين الألم.',
      type: ProcedureType.interventional,
      duration: '45-60 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'أسمنت عظمي',
      doseLevel: 'متوسطة',
      indications: [
        'كسر فقري مؤلم',
        'هشاشة العظام',
        'نقائل فقرية',
        'أورام فقرية',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل التخثر',
        'تخدير موضعي',
        'إبرة في الفقرة',
        'حقن الأسمنت',
        'مراقبة بعد',
      ],
      notes: 'يُسكّن الألم في 80-90% من الحالات.',
    ),
    Procedure(
      id: 'ptc',
      icon: '🫃',
      nameEn: 'PTC / PTBD',
      nameAr: 'تصريف القنوات الصفراوية',
      shortDesc:
          'تصريف القنوات الصفراوية عبر الجلد.',
      type: ProcedureType.interventional,
      duration: '60-90 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'يودي',
      doseLevel: 'عالية',
      indications: [
        'انسداد القنوات الصفراوية',
        'اليرقان الانسدادي',
        'التهاب الأقنية الصفراوية',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل',
        'تخدير موضعي',
        'إبرة في الكبد',
        'قسطرة للقناة',
        'تصريف خارجي',
      ],
      notes: 'بديل غير جراحي للانسداد.',
    ),
    Procedure(
      id: 'nephrostomy',
      icon: '🫘',
      nameEn: 'Percutaneous Nephrostomy',
      nameAr: 'تصريف الكلى عبر الجلد',
      shortDesc:
          'تصريف البول مباشرة من الكلى للخارج.',
      type: ProcedureType.interventional,
      duration: '45-60 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'يودي',
      doseLevel: 'متوسطة',
      indications: [
        'انسداد بولي حاد',
        'التهاب كلى مع انسداد',
        'حصى كبيرة',
        'أورام الحوض',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل',
        'تخدير موضعي',
        'إبرة في الكلى',
        'قسطرة تصريف',
      ],
      notes: 'حالة طارئة — يُنقذ الكلى.',
    ),
    Procedure(
      id: 'enteric_stent',
      icon: '🫃',
      nameEn: 'Enteric Stent',
      nameAr: 'دعامة معوية',
      shortDesc:
          'دعامة معدنية لفتح انسداد المريء أو الأمعاء.',
      type: ProcedureType.therapeutic,
      duration: '45 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'يودي + دعامة',
      doseLevel: 'متوسطة',
      indications: [
        'سرطان المريء',
        'سرطان المعدة',
        'انسداد قولوني خبيث',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تخدير موضعي/عام',
        'قسطرة + توجيه',
        'فتح الدعامة',
      ],
      notes: 'للعلاج التلطيفي — يحسّن البلع.',
    ),
  ],
  comparisonHeaders: ['الإجراء', 'المدة', 'الجرعة', 'الأفضل لـ'],
  comparisonTable: [
    ['بلع الباريوم', '15-20 دقيقة', '1-3 mSv', 'البلع والمريء'],
    ['Barium Meal', '30-45 دقيقة', '3-5 mSv', 'المعدة'],
    ['حقنة شرجية', '30-45 دقيقة', '5-8 mSv', 'القولون'],
    ['IVP', '30-60 دقيقة', '5-7 mSv', 'الجهاز البولي'],
    ['قسطرة قلب', '30-60 دقيقة', '5-15 mSv', 'الشرايين التاجية'],
    ['رأب الأوعية', '45-90 دقيقة', '10-30 mSv', 'التضيّقات'],
    ['TACE', '60-90 دقيقة', 'عالية', 'سرطان الكبد'],
    ['TIPS', '90-120 دقيقة', 'عالية', 'دوالي المريء'],
    ['إغلاق الأوعية', '60-120 دقيقة', 'عالية', 'نزيف وأورام'],
    ['Vertebroplasty', '45-60 دقيقة', 'متوسطة', 'كسور فقرية'],
    ['PTBD', '60-90 دقيقة', 'عالية', 'انسداد صفراوي'],
    ['Nephrostomy', '45-60 دقيقة', 'متوسطة', 'انسداد بولي'],
    ['دعامة معوية', '45 دقيقة', 'متوسطة', 'انسداد خبيث'],
  ],
);