import '../procedure_model.dart';

const ProceduresData laserProcedures = ProceduresData(
  deviceId: 'laser',
  intro:
      'الليزر الطبي له استخدامات في كل التخصصات تقريباً. كل نوع له طول موجي '
      'وخصائص مختلفة. الجلسات سريعة عادة (15-60 دقيقة).',
  procedures: [
    Procedure(
      id: 'lasik',
      icon: '👁️',
      nameEn: 'LASIK',
      nameAr: 'تصحيح الإبصار (LASIK)',
      shortDesc:
          'تصحيح قصر النظر وطوله والاستجماتيزم. بليزر Excimer.',
      type: ProcedureType.therapeutic,
      duration: '15-30 دقيقة للعينين',
      preparation: 'إيقاف العدسات اللاصقة',
      contrast: 'قطرات مخدرة',
      doseLevel: 'لا يوجد',
      indications: [
        'قصر النظر (-1 إلى -10)',
        'طول النظر (+1 إلى +4)',
        'الاستجماتيزم',
        'رغبة التخلص من النظارات',
      ],
      preparationSteps: [
        'إيقاف العدسات 2-4 أسابيع',
        'فحص قرنية شامل',
        'قطرات مخدرة',
        'تثبيت العين',
        'الليزر يشكّل القرنية',
      ],
      notes: 'النتيجة فورية — إبصار 20/20 عادة.',
    ),
    Procedure(
      id: 'cataract_laser',
      icon: '👁️',
      nameEn: 'Laser Cataract Surgery',
      nameAr: 'إزالة الساد بالليزر',
      shortDesc:
          'استخدام ليزر الفيمتوثانية لإزالة عدسة العين المعتمة.',
      type: ProcedureType.therapeutic,
      duration: '20-30 دقيقة',
      preparation: 'قطرات موسّعة للحدقة',
      contrast: 'بدون',
      doseLevel: 'لا يوجد',
      indications: [
        'الساد (Cataract)',
        'ضعف إبصار تدريجي',
      ],
      preparationSteps: [
        'قطرات موسّعة',
        'تخدير موضعي',
        'ليزر يفتت العدسة',
        'شفط العدسة',
        'زرع عدسة صناعية',
      ],
      notes: 'أدق من الجراحة التقليدية.',
    ),
    Procedure(
      id: 'retinal_laser',
      icon: '👁️',
      nameEn: 'Retinal Laser (PRP)',
      nameAr: 'ليزر الشبكية',
      shortDesc:
          'لعلاج الشبكية السكرية والجلوكوما. يوقف تسرب الأوعية.',
      type: ProcedureType.therapeutic,
      duration: '20-40 دقيقة',
      preparation: 'قطرات موسّعة',
      contrast: 'بدون',
      doseLevel: 'لا يوجد',
      indications: [
        'اعتلال شبكية سكري',
        'تمزق الشبكية',
        'الجلوكوما',
        'انسداد الأوعية الشبكية',
      ],
      preparationSteps: [
        'قطرات موسّعة',
        'تخدير موضعي',
        'ليزر Argon أو Diode',
        'عدة مئات من النبضات',
      ],
      notes: 'قد يحتاج جلسات متعددة. يُنقذ البصر.',
    ),
    Procedure(
      id: 'hair_removal',
      icon: '🧴',
      nameEn: 'Laser Hair Removal',
      nameAr: 'إزالة الشعر بالليزر',
      shortDesc:
          'الأكثر طلباً في التجميل. يُدمّر بصيلات الشعر بالحرارة.',
      type: ProcedureType.therapeutic,
      duration: '15-60 دقيقة',
      preparation: 'إزالة الشعر بالحلاقة قبل يوم',
      contrast: 'بدون',
      doseLevel: 'لا يوجد',
      indications: [
        'شعر زائد في الوجه',
        'شعر الجسم الزائد',
        'الشعر تحت الجلد',
        'الرغبة في تقليل الشعر',
      ],
      preparationSteps: [
        'حلاقة الشعر قبل 24 ساعة',
        'تجنّب الشمس 2 أسابيع',
        'تخدير موضعي (اختياري)',
        'نظارات واقية',
        'عدة نبضات على المنطقة',
      ],
      notes: 'يحتاج 6-8 جلسات — الشعر الداكن الأكثر استجابة.',
    ),
    Procedure(
      id: 'tattoo_removal',
      icon: '🎨',
      nameEn: 'Laser Tattoo Removal',
      nameAr: 'إزالة الوشم بالليزر',
      shortDesc:
          'ليزر Q-Switched يفتت حبر الوشم تدريجياً.',
      type: ProcedureType.therapeutic,
      duration: '15-30 دقيقة',
      preparation: 'بدون تحضير خاص',
      contrast: 'تخدير موضعي',
      doseLevel: 'لا يوجد',
      indications: [
        'وشم قديم',
        'وشم غير مرغوب',
        'ندم على الوشم',
      ],
      preparationSteps: [
        'تخدير موضعي',
        'نظارات واقية',
        'نبضات Q-Switched',
        'كمادات باردة بعد',
      ],
      notes: 'الوشم الأزرق والأسود الأسهل. الأحمر والأصفر أصعب.',
    ),
    Procedure(
      id: 'skin_resurfacing',
      icon: '✨',
      nameEn: 'Fractional Laser Resurfacing',
      nameAr: 'تجديد البشرة بالليزر',
      shortDesc:
          'لتجديد البشرة، التجاعيد، الندبات، وحب الشباب.',
      type: ProcedureType.therapeutic,
      duration: '30-60 دقيقة',
      preparation: 'كريم مخدر 45 دقيقة',
      contrast: 'بدون',
      doseLevel: 'لا يوجد',
      indications: [
        'تجاعيد الوجه',
        'ندبات حب الشباب',
        'تصبغات',
        'توسع المسامات',
        'ترهلات بسيطة',
      ],
      preparationSteps: [
        'كريم مخدر موضعي',
        'تنظيف الوجه',
        'عدة تمريرات بالليزر',
        'كمادات باردة',
        'كريم مرطب',
      ],
      notes: 'يحتاج 3-5 جلسات. الاحمرار يختفي خلال أيام.',
    ),
    Procedure(
      id: 'vascular_laser',
      icon: '🩸',
      nameEn: 'Vascular Laser',
      nameAr: 'ليزر الأوعية الدموية',
      shortDesc:
          'لعلاج الأوعية الشعرية، الدوالي الصغيرة، والوحمات.',
      type: ProcedureType.therapeutic,
      duration: '15-45 دقيقة',
      preparation: 'بدون تحضير خاص',
      contrast: 'بدون',
      doseLevel: 'لا يوجد',
      indications: [
        'الأوعية الشعرية (Spider veins)',
        'الوحمات الوعائية',
        'الوردية (Rosacea)',
        'أوعية الوجه',
      ],
      preparationSteps: [
        'تنظيف المنطقة',
        'نظارات واقية',
        'نبضات على الأوعية',
        'كمادات باردة',
      ],
      notes: 'آمن للوجه. يحتاج جلسات متعددة.',
    ),
    Procedure(
      id: 'dental_laser',
      icon: '🦷',
      nameEn: 'Dental Laser',
      nameAr: 'ليزر الأسنان',
      shortDesc:
          'لجراحة اللثة، علاج التسوس، وتنظيف الجيوب.',
      type: ProcedureType.therapeutic,
      duration: '15-45 دقيقة',
      preparation: 'حسب الإجراء',
      contrast: 'تخدير موضعي',
      doseLevel: 'لا يوجد',
      indications: [
        'جراحة اللثة',
        'علاج التسوس',
        'تنظيف الجيوب',
        'إزالة اللثة الزائدة',
      ],
      preparationSteps: [
        'تخدير موضعي',
        'نظارات واقية',
        'تطبيق الليزر',
        'تعليمات بعد الإجراء',
      ],
      notes: 'أقل ألماً وأسرع شفاء من الجراحة التقليدية.',
    ),
    Procedure(
      id: 'urology_laser',
      icon: '🫘',
      nameEn: 'HoLEP / Laser Lithotripsy',
      nameAr: 'ليزر المسالك البولية',
      shortDesc:
          'استئصال البروستاتا بالليزر وتفتيت الحصى.',
      type: ProcedureType.therapeutic,
      duration: '60-120 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'تخدير عام',
      doseLevel: 'لا يوجد',
      indications: [
        'تضخم البروستاتا الحميد',
        'حصى الكلى والحالب',
        'حصى المثانة',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل',
        'تخدير عام',
        'إجراء بالمنظار',
        'قسطرة بعد الإجراء',
      ],
      notes: 'HoLEP أفضل من TURP التقليدي — نزيف أقل.',
    ),
    Procedure(
      id: 'pdt',
      icon: '🎗️',
      nameEn: 'PDT (Photodynamic Therapy)',
      nameAr: 'العلاج الديناميكي الضوئي',
      shortDesc:
          'دواء حساس للضوء + ليزر. للسرطانات السطحية.',
      type: ProcedureType.therapeutic,
      duration: '30-60 دقيقة',
      preparation: 'حقن دواء حساس للضوء',
      contrast: 'Photofrin أو ALA',
      doseLevel: 'لا يوجد',
      indications: [
        'سرطان المريء المبكر',
        'سرطان الرئة المبكر',
        'سرطان الجلد',
        'القرنية السطحية',
      ],
      preparationSteps: [
        'حقن دواء حساس للضوء',
        'انتظار 24-48 ساعة (يتراكم في الورم)',
        'تسليط الليزر على الورم',
        'البقاء بعيداً عن الشمس أسابيع',
      ],
      notes: 'الخلايا السرطانية فقط تمتص الدواء.',
    ),
    Procedure(
      id: 'ent_laser',
      icon: '🩺',
      nameEn: 'ENT Laser',
      nameAr: 'ليزر الأنف والأذن والحنجرة',
      shortDesc:
          'لعلاج اللحمية، الحبال الصوتية، والشخير.',
      type: ProcedureType.therapeutic,
      duration: '15-60 دقيقة',
      preparation: 'حسب الإجراء',
      contrast: 'تخدير موضعي أو عام',
      doseLevel: 'لا يوجد',
      indications: [
        'اللحمية والزوائد',
        'عقيدات الحبال الصوتية',
        'الشخير',
        'أورام حنجرية صغيرة',
      ],
      preparationSteps: [
        'حسب الإجراء',
        'نظارات واقية',
        'الليزر CO₂ عادة',
        'تعليمات ما بعد الجراحة',
      ],
      notes: 'CO₂ Laser الأكثر استخداماً في ENT.',
    ),
    Procedure(
      id: 'proctology_laser',
      icon: '🩺',
      nameEn: 'Proctology Laser',
      nameAr: 'ليزر الشرج والمستقيم',
      shortDesc:
          'لعلاج البواسير، الشق الشرجي، والنواسير.',
      type: ProcedureType.therapeutic,
      duration: '20-45 دقيقة',
      preparation: 'حقنة شرجية + صيام',
      contrast: 'تخدير موضعي/عام',
      doseLevel: 'لا يوجد',
      indications: [
        'البواسير',
        'الشق الشرجي',
        'النواسير',
        'الزوائد الشرجية',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'حقنة شرجية',
        'تخدير',
        'إجراء بالليزر',
        'تعليمات ما بعد الجراحة',
      ],
      notes: 'أقل ألماً وأسرع شفاء من الجراحة التقليدية.',
    ),
  ],
  comparisonHeaders: ['النوع', 'المدة', 'الجلسات', 'الأفضل لـ'],
  comparisonTable: [
    ['LASIK', '15-30 دقيقة', '1', 'تصحيح الإبصار'],
    ['الساد', '20-30 دقيقة', '1', 'العدسة المعتمة'],
    ['شبكية', '20-40 دقيقة', '3-6', 'اعتلال سكري'],
    ['إزالة شعر', '15-60 دقيقة', '6-8', 'الشعر الزائد'],
    ['إزالة وشم', '15-30 دقيقة', '6-10', 'الوشم'],
    ['تجديد بشرة', '30-60 دقيقة', '3-5', 'التجاعيد'],
    ['أوعية', '15-45 دقيقة', '2-6', 'الأوعية الشعرية'],
    ['أسنان', '15-45 دقيقة', '1-3', 'اللثة والتسوس'],
    ['مسالك', '60-120 دقيقة', '1', 'بروستاتا وحصى'],
    ['PDT', '30-60 دقيقة', '1-3', 'سرطانات سطحية'],
    ['ENT', '15-60 دقيقة', '1-2', 'لحمية وشخير'],
    ['Proctology', '20-45 دقيقة', '1', 'بواسير'],
  ],
);