import '../procedure_model.dart';

const ProceduresData mammographyProcedures = ProceduresData(
  deviceId: 'mammo',
  intro:
      'Mammography له أنواع مختلفة: الفحص الدوري، التشخيصي، DBT، والخزعة '
      'الموجهة. الفحوصات سريعة (20 دقيقة) وحاسمة للكشف المبكر.',
  procedures: [
    Procedure(
      id: 'screening_mammo',
      icon: '🔍',
      nameEn: 'Screening Mammography',
      nameAr: 'Mammography دوري',
      shortDesc:
          'الفحص الدوري للنساء 40+ بدون أعراض. 4 صور قياسية.',
      type: ProcedureType.diagnostic,
      duration: '20 دقيقة',
      preparation: 'بدون مزيل عرق',
      contrast: 'بدون',
      doseLevel: 'منخفضة (0.4 mSv)',
      indications: [
        'النساء 40-74 سنة',
        'كل 1-2 سنة',
        'بدون أعراض',
      ],
      preparationSteps: [
        'بدون مزيل عرق أو بودرة',
        'ملابس من قطعة واحدة',
        'إحضار الصور السابقة',
        '4 صور (2 لكل ثدي)',
      ],
      notes: 'يُقلل وفيات سرطان الثدي بنسبة 30%.',
    ),
    Procedure(
      id: 'diagnostic_mammo',
      icon: '🩺',
      nameEn: 'Diagnostic Mammography',
      nameAr: 'Mammography تشخيصي',
      shortDesc:
          'للكشف عن كتلة أو أعراض. صور إضافية + تكبير.',
      type: ProcedureType.diagnostic,
      duration: '30 دقيقة',
      preparation: 'بدون مزيل عرق',
      contrast: 'بدون',
      doseLevel: 'منخفضة (0.6 mSv)',
      indications: [
        'كتلة محسوسة',
        'إفرازات حلمة',
        'ألم ثدي',
        'تغيّر جلدي',
        'متابعة بعد سرطان',
      ],
      preparationSteps: [
        'بدون مزيل عرق',
        'إحضار الصور السابقة',
        '4-6 صور مع Magnification',
        'قد يحتاج Ultrasound',
      ],
      notes: 'أكثر تفصيلاً من الفحص الدوري.',
    ),
    Procedure(
      id: 'dbt',
      icon: '📸',
      nameEn: 'DBT (Tomosynthesis)',
      nameAr: 'التصوير المقطعي للثدي',
      shortDesc:
          '3D Mammography. يقلل النداءات الكاذبة ويحسّن الكشف.',
      type: ProcedureType.diagnostic,
      duration: '25 دقيقة',
      preparation: 'بدون مزيل عرق',
      contrast: 'بدون',
      doseLevel: 'منخفضة (0.5 mSv)',
      indications: [
        'نفس الفحص الدوري',
        'الثدي الكثيف',
        'تاريخ عائلي',
      ],
      preparationSteps: [
        'مثل Mammography العادي',
        'التصوير من زوايا متعددة',
        'إعادة بناء 3D',
      ],
      notes: 'المعيار الحديث — أفضل من FFDM التقليدي.',
    ),
    Procedure(
      id: 'contrast_mammo',
      icon: '💉',
      nameEn: 'Contrast-Enhanced Mammography (CEM)',
      nameAr: 'Mammography مع تباين',
      shortDesc:
          'Mammography مع تباين يودي. بديل أرخص من MRI.',
      type: ProcedureType.diagnostic,
      duration: '30 دقيقة',
      preparation: 'قياس كرياتينين',
      contrast: 'وريدي (يودي)',
      doseLevel: 'منخفضة-متوسطة',
      indications: [
        'الثدي الكثيف',
        'تقييم قبل الجراحة',
        'مرضى لا يتحملون MRI',
      ],
      preparationSteps: [
        'قياس الكرياتينين',
        'كانيولا وريدية',
        'حقن التباين',
        'تصوير قبل وبعد',
      ],
      notes: 'يحسّن الكشف بنسبة 10-15% مقارنة بـ DBT.',
    ),
    Procedure(
      id: 'stereotactic_biopsy',
      icon: '💉',
      nameEn: 'Stereotactic Biopsy',
      nameAr: 'خزعة استيريوتكتيكية',
      shortDesc:
          'خزعة موجهة للتكلّسات الدقيقة. دقة عالية.',
      type: ProcedureType.interventional,
      duration: '45 دقيقة',
      preparation: 'بدون مضادات تخثر',
      contrast: 'تخدير موضعي',
      doseLevel: 'منخفضة',
      indications: [
        'تكلّسات دقيقة مشبوهة',
        'آفات غير محسوسة',
        'BI-RADS 4',
      ],
      preparationSteps: [
        'إيقاف مضادات التخثر',
        'وضعية Prone',
        'صورتان بزاويتين',
        'توجيه الإبرة',
        'سحب 6-12 عينة',
      ],
      notes: 'أدق من الجراحة المفتوحة. أقل ندبة.',
    ),
    Procedure(
      id: 'us_guided_biopsy',
      icon: '💉',
      nameEn: 'Ultrasound-Guided Biopsy',
      nameAr: 'خزعة موجهة بالـ Ultrasound',
      shortDesc:
          'خزعة موجهة بـ Ultrasound للكتل المحسوسة.',
      type: ProcedureType.interventional,
      duration: '30 دقيقة',
      preparation: 'بدون مضادات تخثر',
      contrast: 'تخدير موضعي',
      doseLevel: 'صفر',
      indications: [
        'كتلة محسوسة',
        'آفات مرئية بالـ US',
        'BI-RADS 4-5',
      ],
      preparationSteps: [
        'إيقاف مضادات التخثر',
        'تخدير موضعي',
        'توجيه بـ US',
        'سحب 4-6 عينات',
        'ضمادة بعد',
      ],
      notes: 'أسرع وأسهل من الاستيريوتكتيك.',
    ),
    Procedure(
      id: 'mri_guided_biopsy',
      icon: '🧲',
      nameEn: 'MRI-Guided Biopsy',
      nameAr: 'خزعة موجهة بالـ MRI',
      shortDesc:
          'للآفات التي لا تظهر في Mammography أو Ultrasound.',
      type: ProcedureType.interventional,
      duration: '60-90 دقيقة',
      preparation: 'مثل MRI',
      contrast: 'Gadolinium + تخدير',
      doseLevel: 'صفر إشعاع',
      indications: [
        'آفات MRI فقط',
        'آفات مشبوهة بالـ MRI',
        'BI-RADS 4-5 في MRI',
      ],
      preparationSteps: [
        'استبيان أمان MRI',
        'حقن Gadolinium',
        'تصوير لتحديد الموقع',
        'توجيه الإبرة',
        'سحب العينة',
      ],
      notes: 'الأعقد — يحتاج فريقاً متخصصاً.',
    ),
    Procedure(
      id: 'localization',
      icon: '🎯',
      nameEn: 'Wire Localization',
      nameAr: 'تحديد موضع الورم قبل الجراحة',
      shortDesc:
          'وضع سلك صغير لتحديد موضع الآفة للجراح.',
      type: ProcedureType.interventional,
      duration: '30 دقيقة',
      preparation: 'حسب الحالة',
      contrast: 'تخدير موضعي',
      doseLevel: 'منخفضة',
      indications: [
        'آفات غير محسوسة قبل الجراحة',
        'DCIS',
        'أورام صغيرة',
      ],
      preparationSteps: [
        'تحديد الموقع بالتصوير',
        'تخدير موضعي',
        'إدخال سلك رفيع',
        'الجراح يتبع السلك',
      ],
      notes: 'يُستخدم مع الجراحة التحفظية.',
    ),
    Procedure(
      id: 'galactography',
      icon: '💧',
      nameEn: 'Galactography',
      nameAr: 'تصوير القنوات اللبنية',
      shortDesc:
          'تصوير القنوات بإدخال تباين — للإفرازات.',
      type: ProcedureType.diagnostic,
      duration: '30 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'تباين يودي في القناة',
      doseLevel: 'منخفضة',
      indications: [
        'إفرازات حلمة دموية',
        'انسداد القنوات',
        'التهاب القنوات',
      ],
      preparationSteps: [
        'تحديد القناة المُفرزة',
        'إدخال قسطرة دقيقة',
        'حقن تباين',
        'تصوير',
      ],
      notes: 'نادر — لكنه مفيد في حالات الإفرازات.',
    ),
    Procedure(
      id: 'implant_mammo',
      icon: '💧',
      nameEn: 'Implant Mammography',
      nameAr: 'Mammography للزرعات',
      shortDesc:
          'تقنية خاصة لفحص الثدي مع زرعات (Silicon/Saline).',
      type: ProcedureType.diagnostic,
      duration: '30 دقيقة',
      preparation: 'بدون مزيل عرق',
      contrast: 'بدون',
      doseLevel: 'منخفضة (0.6 mSv)',
      indications: [
        'متابعة زرعة الثدي',
        'كشف تمزق الزرعة',
        'كشف سرطان مع زرعة',
      ],
      preparationSteps: [
        '4 صور قياسية + 4 صور Implant Displacement',
        'ضغط لطيف على الزرعة',
        'تصوير إضافي إن لزم',
      ],
      notes: 'يحتاج ضغطاً لطيفاً — الزرعة قابلة للتمزق.',
    ),
    Procedure(
      id: 'male_mammo',
      icon: '🩺',
      nameEn: 'Male Mammography',
      nameAr: 'Mammography للرجال',
      shortDesc:
          'لتقييم تضخم الثدي عند الرجال (Gynecomastia) أو الكتل.',
      type: ProcedureType.diagnostic,
      duration: '20 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'بدون',
      doseLevel: 'منخفضة جداً',
      indications: [
        'تضخم الثدي (Gynecomastia)',
        'كتلة في الثدي',
        'ألم في الثدي',
        'سرطان الثدي (نادر)',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'صورتان لكل ثدي عادة',
        'قد يحتاج Ultrasound',
      ],
      notes: 'سرطان الثدي عند الرجال نادر لكنه موجود.',
    ),
    Procedure(
      id: 'specimen_mammo',
      icon: '🔬',
      nameEn: 'Specimen Mammography',
      nameAr: 'Mammography للعينة',
      shortDesc:
          'تصوير العينة بعد الجراحة للتأكد من الحدود.',
      type: ProcedureType.diagnostic,
      duration: '15 دقيقة',
      preparation: 'في المختبر',
      contrast: 'بدون',
      doseLevel: 'منخفضة',
      indications: [
        'التأكد من استئصال الورم كاملاً',
        'تحديد الهوامش',
        'توجيه الفحص المجهري',
      ],
      preparationSteps: [
        'تصوير العينة المستأصلة',
        'تحديد الهوامش',
        'تقرير للجراح',
      ],
      notes: 'يُجرى أثناء العملية أو بعدها مباشرة.',
    ),
  ],
  comparisonHeaders: ['الفحص', 'المدة', 'الجرعة', 'الأفضل لـ'],
  comparisonTable: [
    ['دوري', '20 دقيقة', '0.4 mSv', 'فحص سنوي'],
    ['تشخيصي', '30 دقيقة', '0.6 mSv', 'كتلة أو أعراض'],
    ['DBT', '25 دقيقة', '0.5 mSv', 'المعيار الحديث'],
    ['CEM', '30 دقيقة', 'منخفضة', 'الثدي الكثيف'],
    ['خزعة استيريوتكتيكية', '45 دقيقة', 'منخفضة', 'تكلّسات دقيقة'],
    ['خزعة US', '30 دقيقة', 'صفر', 'كتل محسوسة'],
    ['خزعة MRI', '60-90 دقيقة', 'صفر', 'آفات MRI فقط'],
    ['تحديد سلك', '30 دقيقة', 'منخفضة', 'قبل الجراحة'],
    ['قنوات لبنية', '30 دقيقة', 'منخفضة', 'إفرازات'],
    ['زرعات', '30 دقيقة', '0.6 mSv', 'متابعة زرعة'],
    ['رجال', '20 دقيقة', 'منخفضة جداً', 'Gynecomastia'],
    ['عينة', '15 دقيقة', 'منخفضة', 'بعد الجراحة'],
  ],
);