import '../procedure_model.dart';

const ProceduresData mriProcedures = ProceduresData(
  deviceId: 'mri',
  intro:
      'MRI له عشرات التسلسلات والبروتوكولات. كل منطقة لها بروتوكولها الخاص. '
      'نذكر هنا الأنواع الرئيسية الأكثر استخداماً.',
  procedures: [
    Procedure(
      id: 'mri_brain',
      icon: '🧠',
      nameEn: 'MRI Brain (Standard)',
      nameAr: 'MRI دماغ قياسي',
      shortDesc:
          'MRI دماغ مع تسلسلات متعددة (T1, T2, FLAIR, DWI). الفحص الذهبي للدماغ.',
      type: ProcedureType.diagnostic,
      duration: '30-45 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'اختياري (Gadolinium)',
      doseLevel: 'صفر إشعاع',
      indications: [
        'أورام دماغية',
        'التصلب المتعدد (MS)',
        'جلطات ونسيج دماغي',
        'الصرع',
        'الصداع المزمن',
        'الالتهابات',
      ],
      preparationSteps: [
        'استبيان أمان MRI كامل',
        'خلع كل المعادن',
        'سدادات أذن',
        'كانيولا وريدية (للتباين)',
        'البقاء ساكناً تماماً',
      ],
      notes: 'يساعد في كشف تفاصيل لا تُرى بـ CT — خصوصاً المادة البيضاء.',
    ),
    Procedure(
      id: 'mri_spine',
      icon: '🦴',
      nameEn: 'MRI Spine',
      nameAr: 'MRI العمود الفقري',
      shortDesc:
          'MRI للعمود الفقري (عنقي، صدري، قطني). الأفضل لآلام الظهر المزمنة.',
      type: ProcedureType.diagnostic,
      duration: '30-45 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'اختياري',
      doseLevel: 'صفر إشعاع',
      indications: [
        'انزلاق غضروفي',
        'تضيّق القناة الشوكية',
        'أورام العمود',
        'التهابات الفقرات',
        'إصابات الحبل الشوكي',
      ],
      preparationSteps: [
        'استبيان أمان MRI',
        'خلع المعادن',
        'الاستلقاء على الظهر',
        'البقاء ساكناً',
      ],
      notes: 'MRI هو الفحص الذهبي لآلام الظهر المزمنة مع أعراض عصبية.',
    ),
    Procedure(
      id: 'mri_joint',
      icon: '🦵',
      nameEn: 'MRI Joint',
      nameAr: 'MRI المفاصل',
      shortDesc:
          'MRI للركبة، الكتف، الرسغ، الكاحل. يُظهر الأربطة والغضاريف بدقة.',
      type: ProcedureType.diagnostic,
      duration: '30 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'نادراً',
      doseLevel: 'صفر إشعاع',
      indications: [
        'تمزق الرباط الصليبي (ACL)',
        'تمزق الغضروف الهلالي',
        'التهاب الأوتار',
        'إصابات رياضية',
        'ألم مفصل مزمن',
      ],
      preparationSteps: [
        'استبيان أمان MRI',
        'خلع المعادن',
        'وضع المفصل في الملف المخصص',
        'البقاء ساكناً',
      ],
      notes: 'MRI أفضل من CT للمفاصل — يُظهر الأنسجة الرخوة بوضوح.',
    ),
    Procedure(
      id: 'mri_liver',
      icon: '🩻',
      nameEn: 'MRI Liver (With Contrast)',
      nameAr: 'MRI الكبد مع تباين',
      shortDesc:
          'MRI للكبد مع تباين كبدي خاص. يُميز بين الأورام الحميدة والخبيثة.',
      type: ProcedureType.diagnostic,
      duration: '45 دقيقة',
      preparation: 'صيام 4-6 ساعات',
      contrast: 'وريدي (Gadolinium)',
      doseLevel: 'صفر إشعاع',
      indications: [
        'أورام الكبد',
        'الورم الوعائي (Hemangioma)',
        'تليف الكبد',
        'الكبد الدهني',
        'نقائل كبدية',
      ],
      preparationSteps: [
        'صيام 4-6 ساعات',
        'استبيان أمان MRI',
        'وظائف الكلى (eGFR > 30)',
        'كانيولا وريدية',
        'حبس النفس المتكرر',
      ],
      notes: 'MRI + تباين كبدي = الأفضل لتشخيص أورام الكبد.',
    ),
    Procedure(
      id: 'mrcp',
      icon: '🫃',
      nameEn: 'MRCP',
      nameAr: 'تصوير القنوات الصفراوية',
      shortDesc:
          'MRI خاص للقنوات الصفراوية والبنكرياس. بدون تباين.',
      type: ProcedureType.diagnostic,
      duration: '20-30 دقيقة',
      preparation: 'صيام 4-6 ساعات',
      contrast: 'بدون',
      doseLevel: 'صفر إشعاع',
      indications: [
        'حصى القناة الصفراوية',
        'تضيّق القنوات',
        'التهاب البنكرياس',
        'أورام البنكرياس',
        'تشوهات خلقية',
      ],
      preparationSteps: [
        'صيام 4-6 ساعات',
        'استبيان أمان MRI',
        'بدون تباين',
        'حبس النفس المتكرر',
      ],
      notes: 'بديل غير توغلي لـ ERCP التشخيصي.',
    ),
    Procedure(
      id: 'mri_prostate',
      icon: '🩺',
      nameEn: 'Multiparametric MRI Prostate',
      nameAr: 'MRI البروستاتا متعدد المعايير',
      shortDesc:
          'MRI متقدم للبروستاتا. يُقيّم الأورام بدقة ويوجه الخزعة.',
      type: ProcedureType.diagnostic,
      duration: '45 دقيقة',
      preparation: 'حسب المركز',
      contrast: 'وريدي',
      doseLevel: 'صفر إشعاع',
      indications: [
        'ارتفاع PSA',
        'خزعة سلبية مع شك',
        'تحديد مرحلة سرطان البروستاتا',
        'متابعة بعد العلاج',
      ],
      preparationSteps: [
        'حسب بروتوكول المركز',
        'حقنة شرجية قد تُطلب',
        'استبيان أمان MRI',
        'كانيولا وريدية',
        'ملف استقبال مخصص',
      ],
      notes: 'PI-RADS تصنيف لتقييم خطر السرطان.',
    ),
    Procedure(
      id: 'mri_breast',
      icon: '🎗️',
      nameEn: 'MRI Breast',
      nameAr: 'MRI الثدي',
      shortDesc:
          'MRI للثدي مع تباين. للنساء عاليات الخطورة والفحص المكمل.',
      type: ProcedureType.diagnostic,
      duration: '45 دقيقة',
      preparation: 'حسب توقيت الدورة',
      contrast: 'وريدي (Gadolinium)',
      doseLevel: 'صفر إشعاع',
      indications: [
        'BRCA1/2 موجب',
        'تاريخ عائلي قوي',
        'زرعات ثدي (تكبير)',
        'متابعة بعد سرطان ثدي',
        'كشف النقائل',
      ],
      preparationSteps: [
        'حسب توقيت الدورة (يوم 7-14)',
        'استبيان أمان MRI',
        'كانيولا وريدية',
        'ملف استقبال ثدي مخصص',
      ],
      notes: 'الأكثر حساسية (90-95%) لكنه ليس بديلاً عن Mammography.',
    ),
    Procedure(
      id: 'fmri',
      icon: '🧠',
      nameEn: 'Functional MRI (fMRI)',
      nameAr: 'MRI وظيفي (fMRI)',
      shortDesc:
          'يقيس نشاط الدماغ بمراقبة تدفق الدم. للجراحات الدماغية والأبحاث.',
      type: ProcedureType.functional,
      duration: '45-60 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'صفر إشعاع',
      indications: [
        'تخطيط جراحة الدماغ',
        'تقييم وظائف الحركة واللغة',
        'أبحاث علمية',
        'اضطرابات عصبية',
      ],
      preparationSteps: [
        'استبيان أمان MRI',
        'تدريب على المهام',
        'سماعات لعرض المهام',
        'البقاء ساكناً تماماً',
      ],
      notes: 'يُظهر المناطق النشطة عند القيام بمهمة (BOLD signal).',
    ),
    Procedure(
      id: 'mra',
      icon: '🩸',
      nameEn: 'MR Angiography (MRA)',
      nameAr: 'تصوير الأوعية بالـ MRI',
      shortDesc:
          'تصوير الشرايين بالرنين. يمكن بدون تباين أو مع تباين.',
      type: ProcedureType.diagnostic,
      duration: '30-45 دقيقة',
      preparation: 'حسب النوع',
      contrast: 'اختياري',
      doseLevel: 'صفر إشعاع',
      indications: [
        'تضيّق الشرايين السباتية',
        'أم الدم الدماغية',
        'تشوهات الأوعية',
        'تقييم الكلى',
        'تقييم الشرايين الطرفية',
      ],
      preparationSteps: [
        'استبيان أمان MRI',
        'كانيولا وريدية (للتباين)',
        'البقاء ساكناً',
      ],
      notes: 'MRA أفضل من CTA في: بدون إشعاع، ولا حاجة لتباين يودي.',
    ),
    Procedure(
      id: 'cardiac_mri',
      icon: '❤️',
      nameEn: 'Cardiac MRI',
      nameAr: 'MRI القلب',
      shortDesc:
          'MRI للقلب مع ECG Gating. يُظهر العضلة، الصمامات، والتروية.',
      type: ProcedureType.diagnostic,
      duration: '60-90 دقيقة',
      preparation: 'صيام 4 ساعات',
      contrast: 'وريدي عادة',
      doseLevel: 'صفر إشعاع',
      indications: [
        'اعتلال عضلة القلب',
        'التهاب التامور',
        'عيوب خلقية',
        'تقييم بعد الجلطة',
        'أورام قلبية',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'استبيان أمان MRI',
        'حلاقة الصدر (لأقطاب ECG)',
        'كانيولا وريدية',
        'حبس النفس المتكرر',
      ],
      notes: 'المعيار الذهبي لقياس وظيفة القلب والكشف عن التليف.',
    ),
    Procedure(
      id: 'mri_guided',
      icon: '💉',
      nameEn: 'MRI-Guided Biopsy',
      nameAr: 'خزعة موجهة بالـ MRI',
      shortDesc:
          'خزعة أو إجراء تداخلي بمساعدة MRI. للأورام غير المرئية بـ CT/US.',
      type: ProcedureType.interventional,
      duration: '60-90 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'حسب الحالة',
      doseLevel: 'صفر إشعاع',
      indications: [
        'أورام البروستاتا',
        'أورام الثدي (في MRI فقط)',
        'أورام الكبد الصغيرة',
        'آفات غير مرئية بـ CT/US',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل التخثر',
        'استبيان أمان MRI',
        'توقيع موافقة',
        'مراقبة بعد الإجراء',
      ],
      notes: 'يحتاج غرفة MRI مخصصة للأدوات اللازمة.',
    ),
  ],
  comparisonHeaders: ['الفحص', 'المدة', 'التباين', 'الأفضل لـ'],
  comparisonTable: [
    ['دماغ', '30-45 دقيقة', 'اختياري', 'الأورام و MS'],
    ['عمود فقري', '30-45 دقيقة', 'اختياري', 'الانزلاق الغضروفي'],
    ['مفاصل', '30 دقيقة', 'نادراً', 'الرباط والغضروف'],
    ['كبد', '45 دقيقة', 'وريدي', 'أورام الكبد'],
    ['MRCP', '20-30 دقيقة', 'بدون', 'القنوات الصفراوية'],
    ['بروستاتا', '45 دقيقة', 'وريدي', 'سرطان البروستاتا'],
    ['ثدي', '45 دقيقة', 'وريدي', 'عالي الخطورة'],
    ['fMRI', '45-60 دقيقة', 'بدون', 'الوظائف الدماغية'],
    ['MRA', '30-45 دقيقة', 'اختياري', 'الأوعية'],
    ['قلب', '60-90 دقيقة', 'وريدي عادة', 'وظيفة القلب'],
  ],
);