import '../procedure_model.dart';

const ProceduresData petProcedures = ProceduresData(
  deviceId: 'pet',
  intro:
      'PET هو فحص وظيفي بأساس نووي. أنواعه تختلف حسب النظير المستخدم والهدف. '
      'أشهرها FDG-PET للأورام. الفحص قد يستغرق 1.5-2 ساعة.',
  procedures: [
    Procedure(
      id: 'fdg_oncology',
      icon: '🎗️',
      nameEn: 'FDG-PET/CT Oncology',
      nameAr: 'PET/CT للأورام',
      shortDesc:
          'الأكثر استخداماً. FDG يُظهر الخلايا عالية الأيض (السرطانية). مع CT للدمج.',
      type: ProcedureType.diagnostic,
      duration: '90-120 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'FDG وريدي',
      doseLevel: 'عالية (15-25 mSv)',
      indications: [
        'تحديد مرحلة السرطان (Staging)',
        'الكشف عن النقائل',
        'تقييم استجابة العلاج',
        'التمييز بين ورم وندبة',
        'تخطيط العلاج الإشعاعي',
      ],
      preparationSteps: [
        'صيام 6 ساعات (ماء فقط)',
        'قياس سكر الدم < 200 mg/dL',
        'إيقاف الأنسولين صباح الفحص',
        'حقن FDG',
        'راحة تامة 45-60 دقيقة',
        'تفريغ المثانة قبل التصوير',
      ],
      notes: 'يُغير قرارات علاجية في ~40% من الحالات.',
    ),
    Procedure(
      id: 'fdg_cardiac',
      icon: '❤️',
      nameEn: 'Cardiac PET',
      nameAr: 'PET القلب',
      shortDesc:
          'تقييم حيوية عضلة القلب بعد الجلطة. يُميز بين حية وميتة.',
      type: ProcedureType.functional,
      duration: '60-90 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'FDG أو Rb-82',
      doseLevel: 'عالية',
      indications: [
        'حيوية عضلة القلب',
        'تقييم قبل إعادة التوعية',
        'التهاب التامور',
        'الساركويد القلبي',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'قياس سكر الدم',
        'استخدام Heparin (يحسّن امتصاص FDG)',
        'تصوير مع ECG Gating',
      ],
      notes: 'يُحدد من سيستفيد من الدعامات أو الجراحة.',
    ),
    Procedure(
      id: 'fdg_brain',
      icon: '🧠',
      nameEn: 'Brain PET',
      nameAr: 'PET الدماغ',
      shortDesc:
          'تقييم الأيض الدماغي. ألزهايمر، صرع، أورام دماغية.',
      type: ProcedureType.functional,
      duration: '60 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'FDG وريدي',
      doseLevel: 'عالية',
      indications: [
        'ألزهايمر المبكر',
        'باركنسون',
        'الصرع (تحديد البؤرة)',
        'الأورام الدماغية',
        'الموت الدماغي',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'راحة تامة في غرفة هادئة',
        'تصوير في بيئة خافتة',
        'عدم الكلام أثناء التصوير',
      ],
      notes: 'يُظهر ألزهايمر قبل ظهور الأعراض بـ 5-10 سنوات.',
    ),
    Procedure(
      id: 'psma_pet',
      icon: '🩺',
      nameEn: 'PSMA PET/CT',
      nameAr: 'PSMA PET/CT للبروستاتا',
      shortDesc:
          'PET متخصص لسرطان البروستاتا. أكثر حساسية من FDG.',
      type: ProcedureType.diagnostic,
      duration: '90 دقيقة',
      preparation: 'صيام 4 ساعات',
      contrast: 'Ga-68 PSMA وريدي',
      doseLevel: 'عالية',
      indications: [
        'ارتفاع PSA بعد العلاج',
        'تحديد مرحلة سرطان البروستاتا',
        'الكشف عن ارتجاع',
        'تقييم قبل الجراحة',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'شرب ماء',
        'حقن PSMA',
        'انتظار 60 دقيقة',
        'تفريغ المثانة',
      ],
      notes: 'أحدث صيحة في تشخيص سرطان البروستاتا.',
    ),
    Procedure(
      id: 'dotatate_pet',
      icon: '🧬',
      nameEn: 'Ga-68 DOTATATE PET',
      nameAr: 'PET للغدد العصبية الصمّاء',
      shortDesc:
          'للأورام العصبية الصمّاء (NETs). يستخدم Ga-68 DOTATATE.',
      type: ProcedureType.diagnostic,
      duration: '90 دقيقة',
      preparation: 'صيام 4 ساعات',
      contrast: 'Ga-68 وريدي',
      doseLevel: 'عالية',
      indications: [
        'الأورام العصبية الصمّاء',
        'أورام الغدة النخامية',
        'تقييم قبل العلاج بالبروتون',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'حقن النظير',
        'انتظار 60 دقيقة',
      ],
      notes: 'يُمكّن من العلاج بـ Lu-177 لاحقاً.',
    ),
    Procedure(
      id: 'amyloid_pet',
      icon: '🧠',
      nameEn: 'Amyloid PET',
      nameAr: 'PET الأميلويد',
      shortDesc:
          'كشف لويحات الأميلويد في الدماغ. لتشخيص ألزهايمر بدقة.',
      type: ProcedureType.diagnostic,
      duration: '60-90 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'F-18 Florbetapir وريدي',
      doseLevel: 'عالية',
      indications: [
        'ألزهايمر (تشخيص دقيق)',
        'التمييز بين ألزهايمر والخرف',
        'البحث العلمي',
      ],
      preparationSteps: [
        'بدون صيام',
        'حقن النظير',
        'انتظار 50 دقيقة',
        'تصوير الدماغ',
      ],
      notes: 'يرتبط بلويحات الأميلويد مباشرة — أكثر حساسية من FDG.',
    ),
    Procedure(
      id: 'fes_pet',
      icon: '🎗️',
      nameEn: 'FES PET (Breast)',
      nameAr: 'PET لسرطان الثدي',
      shortDesc:
          'لتقييم مستقبلات الإستروجين في سرطان الثدي.',
      type: ProcedureType.diagnostic,
      duration: '90 دقيقة',
      preparation: 'صيام 4 ساعات',
      contrast: 'F-18 FES وريدي',
      doseLevel: 'عالية',
      indications: [
        'تقييم ER في سرطان الثدي',
        'الكشف عن النقائل',
        'متابعة العلاج الهرموني',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'حقن النظير',
        'انتظار 60 دقيقة',
      ],
      notes: 'يُساعد في اختيار العلاج الهرموني المناسب.',
    ),
    Procedure(
      id: 'fna_pet',
      icon: '🦴',
      nameEn: 'NaF PET Bone',
      nameAr: 'PET العظام بـ NaF',
      shortDesc:
          'كشف النقائل العظمية بـ NaF PET. أكثر حساسية من Bone Scan.',
      type: ProcedureType.diagnostic,
      duration: '60 دقيقة',
      preparation: 'شرب ماء',
      contrast: 'F-18 NaF وريدي',
      doseLevel: 'عالية',
      indications: [
        'نقائل عظمية',
        'أورام عظمية أولية',
        'تقييم ألم عظمي مجهول',
      ],
      preparationSteps: [
        'شرب ماء كثير',
        'حقن NaF',
        'انتظار 45 دقيقة',
        'تفريغ المثانة',
      ],
      notes: 'أفضل من Bone Scan التقليدي — أكثر حساسية.',
    ),
    Procedure(
      id: 'perfusion_pet',
      icon: '🩸',
      nameEn: 'Perfusion PET',
      nameAr: 'PET التروية',
      shortDesc:
          'قياس تدفق الدم في القلب أو الدماغ بـ O-15 Water.',
      type: ProcedureType.functional,
      duration: '30-45 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'O-15 Water أو N-13 Ammonia',
      doseLevel: 'عالية',
      indications: [
        'تروية عضلة القلب',
        'تروية الدماغ',
        'البحث العلمي',
      ],
      preparationSteps: [
        'بدون صيام',
        'كانيولا وريدية',
        'حقن متكرر مع تصوير فوري',
      ],
      notes: 'عمر النصف قصير جداً (2 دقيقة) — يحتاج Cyclotron قريب.',
    ),
    Procedure(
      id: 'pet_mri',
      icon: '🧲',
      nameEn: 'PET/MRI',
      nameAr: 'PET/MRI المدمج',
      shortDesc:
          'دمج PET مع MRI بدلاً من CT. أفضل للأنسجة الرخوة.',
      type: ProcedureType.diagnostic,
      duration: '60-90 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'FDG + Gadolinium',
      doseLevel: 'متوسطة (أقل من PET/CT)',
      indications: [
        'أورام الدماغ',
        'أورام الأطفال',
        'أورام الكبد',
        'البحث العلمي',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'استبيان أمان MRI',
        'حقن FDG',
        'انتظار 60 دقيقة',
        'تصوير PET/MRI',
      ],
      notes: 'أحدث تقنية — أقل إشعاعاً وأدق للأنسجة الرخوة.',
    ),
    Procedure(
      id: 'fdopa_pet',
      icon: '🧠',
      nameEn: 'F-DOPA PET',
      nameAr: 'PET للدماغ بـ F-DOPA',
      shortDesc:
          'لتقييم الدوبامين في الدماغ. باركنسون والأورام العصبية.',
      type: ProcedureType.functional,
      duration: '90 دقيقة',
      preparation: 'صيام 4 ساعات',
      contrast: 'F-18 DOPA وريدي',
      doseLevel: 'عالية',
      indications: [
        'باركنسون',
        'الأورام العصبية الصمّاء',
        'البحث العلمي',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'إيقاف أدوية باركنسون',
        'حقن النظير',
        'انتظار 60 دقيقة',
      ],
      notes: 'يُقيّم وظيفة الخلايا المنتجة للدوبامين.',
    ),
    Procedure(
      id: 'hypoxia_pet',
      icon: '🫁',
      nameEn: 'Hypoxia PET',
      nameAr: 'PET نقص الأوكسجين',
      shortDesc:
          'كشف مناطق نقص الأوكسجين في الأورام. للعلاج الإشعاعي.',
      type: ProcedureType.functional,
      duration: '90 دقيقة',
      preparation: 'صيام 4 ساعات',
      contrast: 'F-MISO وريدي',
      doseLevel: 'عالية',
      indications: [
        'تخطيط العلاج الإشعاعي',
        'الأورام المقاومة للإشعاع',
        'البحث العلمي',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'حقن F-MISO',
        'انتظار 90-120 دقيقة',
        'تصوير',
      ],
      notes: 'المناطق ناقصة الأوكسجين تحتاج جرعة إشعاعية أعلى.',
    ),
  ],
  comparisonHeaders: ['النوع', 'النظير', 'المدة', 'الأفضل لـ'],
  comparisonTable: [
    ['أورام', 'FDG', '90-120 دقيقة', 'Staging وتقييم'],
    ['قلب', 'FDG/Rb-82', '60-90 دقيقة', 'حيوية القلب'],
    ['دماغ', 'FDG', '60 دقيقة', 'ألزهايمر وصرع'],
    ['بروستاتا', 'PSMA', '90 دقيقة', 'سرطان البروستاتا'],
    ['NETs', 'Ga-68 DOTATATE', '90 دقيقة', 'الأورام الصمّاء'],
    ['أميلويد', 'Florbetapir', '60-90 دقيقة', 'ألزهايمر دقيق'],
    ['ثدي', 'FES', '90 دقيقة', 'ER في الثدي'],
    ['عظام', 'NaF', '60 دقيقة', 'نقائل عظمية'],
    ['تروية', 'O-15', '30-45 دقيقة', 'تدفق الدم'],
    ['PET/MRI', 'FDG', '60-90 دقيقة', 'أنسجة رخوة'],
  ],
);