import '../procedure_model.dart';

const ProceduresData radiotherapyProcedures = ProceduresData(
  deviceId: 'rt',
  intro:
      'العلاج الإشعاعي له أنواع كثيرة — من العلاج الخارجي البسيط إلى SBRT عالي '
      'الدقة. كل نوع له دواعيه الخاصة والجرعة المميزة.',
  procedures: [
    Procedure(
      id: 'ebrt',
      icon: '⚡',
      nameEn: 'EBRT (External Beam RT)',
      nameAr: 'علاج إشعاعي خارجي',
      shortDesc:
          'الأكثر شيوعاً. LINAC يوجه الأشعة من خارج الجسم نحو الورم.',
      type: ProcedureType.therapeutic,
      duration: '10-15 دقيقة/جلسة',
      preparation: 'قوالب تثبيت + تصوير تخطيطي',
      contrast: 'حسب الحالة',
      doseLevel: 'علاجية (60-70 Gy إجمالاً)',
      indications: [
        'سرطان البروستاتا',
        'سرطان الرئة',
        'سرطان الرأس والعنق',
        'سرطان الثدي',
        'سرطان المستقيم',
      ],
      preparationSteps: [
        'تصوير CT للتخطيط',
        'صنع قالب تثبيت',
        'وشم صغير للعلامة',
        'تخطيط على الحاسوب',
        'QA قبل الجلسة',
      ],
      notes: 'يُقسَّم على 20-40 جلسة (Fractionation).',
    ),
    Procedure(
      id: 'imrt',
      icon: '🎛️',
      nameEn: 'IMRT',
      nameAr: 'علاج إشعاعي معدّل الشدة',
      shortDesc:
          'تعديل شدة الأشعة لكل شعاع — يحمي الأعضاء المجاورة.',
      type: ProcedureType.therapeutic,
      duration: '15-20 دقيقة/جلسة',
      preparation: 'تخطيط CT + DVH مثالي',
      contrast: 'حسب الحالة',
      doseLevel: 'علاجية (60-80 Gy)',
      indications: [
        'سرطان البروستاتا',
        'سرطان الرأس والعنق',
        'الأورام القريبة من أعضاء حساسة',
        'سرطان الدماغ',
      ],
      preparationSteps: [
        'CT تخطيطي',
        'تحديد الأهداف والأعضاء',
        'Optimization',
        'QA على Phantom',
      ],
      notes: 'أفضل من 3D-CRT للحفاظ على الأنسجة السليمة.',
    ),
    Procedure(
      id: 'vmat',
      icon: '🌀',
      nameEn: 'VMAT',
      nameAr: 'علاج قوسي معدّل',
      shortDesc:
          'IMRT مع دوران LINAC بشكل قوسي مستمر. الأسرع.',
      type: ProcedureType.therapeutic,
      duration: '5-10 دقائق/جلسة',
      preparation: 'مثل IMRT',
      contrast: 'حسب الحالة',
      doseLevel: 'علاجية',
      indications: [
        'سرطان البروستاتا',
        'سرطان الرأس والعنق',
        'سرطان الرئة',
        'أورام الحوض',
      ],
      preparationSteps: [
        'CT تخطيطي',
        'Optimization',
        'QA',
        'تصوير IGRT قبل الجلسة',
      ],
      notes: 'الأسرع حالياً — دقيقة واحدة للقوس الكامل.',
    ),
    Procedure(
      id: 'sbrt',
      icon: '🎯',
      nameEn: 'SBRT / SABR',
      nameAr: 'العلاج الإشعاعي التجسيمي',
      shortDesc:
          'جرعة عالية جداً بدقة ملّيمترية. 3-5 جلسات فقط.',
      type: ProcedureType.therapeutic,
      duration: '30-60 دقيقة/جلسة',
      preparation: 'قوالب دقيقة + IGRT إلزامي',
      contrast: 'حسب الحالة',
      doseLevel: 'عالية جداً (7-20 Gy/جلسة)',
      indications: [
        'سرطان الرئة المبكر',
        'نقائل الكبد',
        'نقائل الرئة',
        'سرطان البروستاتا الموضعي',
        'نقائل العمود الفقري',
      ],
      preparationSteps: [
        'تثبيت دقيق',
        'تصوير 4D-CT',
        'تخطيط عالي الدقة',
        'IGRT يومي',
      ],
      notes: 'بديل للجراحة في بعض الأورام.',
    ),
    Procedure(
      id: 'srs',
      icon: '🧠',
      nameEn: 'SRS (Gamma Knife)',
      nameAr: 'الجراحة الإشعاعية',
      shortDesc:
          'جرعة عالية في جلسة واحدة لأورام الدماغ الصغيرة.',
      type: ProcedureType.therapeutic,
      duration: '30-90 دقيقة (جلسة واحدة)',
      preparation: 'إطار تثبيت للرأس',
      contrast: 'حسب الحالة',
      doseLevel: 'عالية جداً (15-25 Gy)',
      indications: [
        'أورام الدماغ الصغيرة',
        'تشوهات شريانية وريدية (AVM)',
        'ورم العصب الثامن',
        'نقائل دماغية',
        'ألم العصب الثلاثي',
      ],
      preparationSteps: [
        'تخدير موضعي لإطار الرأس',
        'MRI + CT للتخطيط',
        'تخطيط دقيق على الحاسوب',
        'جلسة واحدة فقط',
      ],
      notes: 'Gamma Knife متخصص للدماغ فقط. CyberKnife للجسم كاملاً.',
    ),
    Procedure(
      id: 'brachytherapy_hdr',
      icon: '💉',
      nameEn: 'HDR Brachytherapy',
      nameAr: 'العلاج الإشعاعي الداخلي عالي الجرعة',
      shortDesc:
          'مصدر مشع عالي النشاط يوضع داخل الورم لدقائق.',
      type: ProcedureType.therapeutic,
      duration: '10-30 دقيقة/جلسة',
      preparation: 'قوالب تطبيق خاصة',
      contrast: 'حسب الحالة',
      doseLevel: 'عالية (Ir-192)',
      indications: [
        'سرطان عنق الرحم',
        'سرطان البروستاتا',
        'سرطان المريء',
        'سرطان الرحم',
      ],
      preparationSteps: [
        'تركيب قوالب التطبيق',
        'تصوير CT للتخطيط',
        'تخطيط الجرعة',
        'Afterloader يدفع المصدر',
        'إزالة القوالب بعد الجلسة',
      ],
      notes: 'الطبيب والطاقم خارج الغرفة أثناء التشغيل.',
    ),
    Procedure(
      id: 'brachytherapy_ldr',
      icon: '💊',
      nameEn: 'LDR Brachytherapy',
      nameAr: 'العلاج الداخلي منخفض الجرعة',
      shortDesc:
          'مصادر مشعة صغيرة تُزرع بشكل دائم في الورم.',
      type: ProcedureType.therapeutic,
      duration: 'زرع دائم',
      preparation: 'تخدير موضعي/عام',
      contrast: 'I-125 أو Pd-103',
      doseLevel: 'منخفضة (مستمرة)',
      indications: [
        'سرطان البروستاتا المبكر',
        'أورام العين',
        'أورام صغيرة',
      ],
      preparationSteps: [
        'تخدير',
        'توجيه بـ Ultrasound',
        'زرع البذور (80-120 بذرة)',
        'تصوير للتأكد',
        'الخروج في نفس اليوم',
      ],
      notes: 'البذور تبقى للأبد لكن إشعاعها ينتهي بعد أشهر.',
    ),
    Procedure(
      id: 'proton_therapy',
      icon: '⚛️',
      nameEn: 'Proton Therapy',
      nameAr: 'العلاج بالبروتونات',
      shortDesc:
          'بروتونات تتوقف عند عمق محدد (Bragg Peak) — حماية أفضل.',
      type: ProcedureType.therapeutic,
      duration: '15-30 دقيقة/جلسة',
      preparation: 'مثل EBRT',
      contrast: 'حسب الحالة',
      doseLevel: 'علاجية',
      indications: [
        'أورام الأطفال',
        'أورام العين',
        'أورام قاعدة الجمجمة',
        'أورام العمود الفقري',
        'سرطان البروستاتا',
      ],
      preparationSteps: [
        'مثل IMRT',
        'تخطيط دقيق بسبب Bragg Peak',
        'QA خاص',
        'جلسات يومية',
      ],
      notes: 'أغلى بكثير من LINAC — لكنه الأفضل للأطفال.',
    ),
    Procedure(
      id: 'ioert',
      icon: '🔪',
      nameEn: 'IORT (Intraoperative RT)',
      nameAr: 'العلاج الإشعاعي أثناء الجراحة',
      shortDesc:
          'جرعة واحدة مباشرة على الورم أثناء العملية.',
      type: ProcedureType.therapeutic,
      duration: '5-15 دقيقة (بعد الاستئصال)',
      preparation: 'في غرفة العمليات',
      contrast: 'حسب الحالة',
      doseLevel: 'عالية (10-20 Gy)',
      indications: [
        'سرطان الثدي (كبديل للجلسات)',
        'سرطان البنكرياس',
        'أورام البطن',
        'ساركوما',
      ],
      preparationSteps: [
        'بعد استئصال الورم',
        'توجيه الأشعة للمنطقة',
        'جرعة واحدة',
        'إغلاق الجرح',
      ],
      notes: 'يُوفّر أسابيع من العلاج بعد الجراحة.',
    ),
    Procedure(
      id: 'palliative_rt',
      icon: '🩹',
      nameEn: 'Palliative RT',
      nameAr: 'العلاج التلطيفي',
      shortDesc:
          'تسكين ألم النقائل والأعراض. جرعات أقل وجلسات أقل.',
      type: ProcedureType.therapeutic,
      duration: '5-15 دقيقة/جلسة',
      preparation: 'بسيط',
      contrast: 'حسب الحالة',
      doseLevel: 'منخفضة-متوسطة (8-30 Gy)',
      indications: [
        'ألم نقائل عظمية',
        'ضغط النخاع الشوكي',
        'نزيف الأورام',
        'انسداد القصبات',
        'ضغط الدماغ',
      ],
      preparationSteps: [
        'تصوير محدد للمنطقة',
        'جلسة-10 جلسات',
        'بدون تخطيط معقد',
      ],
      notes: 'يُحسّن جودة الحياة — الألم يخف خلال 48 ساعة.',
    ),
    Procedure(
      id: 'tsebt',
      icon: '🔴',
      nameEn: 'TSEBT (Total Skin Electron)',
      nameAr: 'العلاج الإشعاعي للجلد كاملاً',
      shortDesc:
          'للمفومة الجلدية T-cell. يُشع الجلد كاملاً.',
      type: ProcedureType.therapeutic,
      duration: '30-40 دقيقة/جلسة',
      preparation: 'وضعيات خاصة متعددة',
      contrast: 'بدون',
      doseLevel: 'متوسطة (30-36 Gy)',
      indications: [
        'المفومة الجلدية T-cell',
        'Mycosis Fungoides',
        'Sézary Syndrome',
      ],
      preparationSteps: [
        '6-8 وضعيات مختلفة',
        'حماية العين والأظافر',
        'جلسات يومية لأسابيع',
      ],
      notes: 'يحتاج تعديل الجرعة حسب سماكة الجلد.',
    ),
    Procedure(
      id: 'radionuclide_therapy',
      icon: '☢️',
      nameEn: 'Radionuclide Therapy',
      nameAr: 'العلاج بالنظائر المشعة',
      shortDesc:
          'نظير مشع ينتقل للورم عبر الدم. I-131، Lu-177، Y-90.',
      type: ProcedureType.therapeutic,
      duration: 'متغير',
      preparation: 'حسب النظير',
      contrast: 'I-131، Lu-177، Y-90، Ra-223',
      doseLevel: 'متغيرة',
      indications: [
        'سرطان الغدة الدرقية (I-131)',
        'NETs (Lu-177)',
        'سرطان الكبد (Y-90)',
        'نقائل بروستاتا (Ra-223)',
      ],
      preparationSteps: [
        'حسب النظير',
        'حماية إشعاعية للمحيطين',
        'شرب ماء كثير',
        'احتياطات لمدة أيام',
      ],
      notes: 'يُعطى عادة عن طريق الفم أو الوريد.',
    ),
  ],
  comparisonHeaders: ['النوع', 'الجرعة', 'الجلسات', 'الأفضل لـ'],
  comparisonTable: [
    ['EBRT', '60-70 Gy', '20-40', 'العلاج الجذري'],
    ['IMRT', '60-80 Gy', '25-40', 'قرب أعضاء حساسة'],
    ['VMAT', '60-80 Gy', '20-40', 'الأسرع'],
    ['SBRT', '7-20 Gy/جلسة', '3-5', 'الأورام الصغيرة'],
    ['SRS', '15-25 Gy', '1', 'دماغ'],
    ['HDR', 'عالية', '3-10', 'عنق الرحم والبروستاتا'],
    ['LDR', 'منخفضة', 'زرع دائم', 'البروستاتا المبكر'],
    ['Proton', 'علاجية', '20-40', 'أطفال وعين'],
    ['IORT', '10-20 Gy', '1', 'أثناء الجراحة'],
    ['Palliative', '8-30 Gy', '1-10', 'تسكين الألم'],
    ['TSEBT', '30-36 Gy', '20-30', 'مفومة جلدية'],
    ['Radionuclide', 'متغيرة', '1-6', 'سرطانات خاصة'],
  ],
);