import '../procedure_model.dart';

const ProceduresData spectProcedures = ProceduresData(
  deviceId: 'spect',
  intro:
      'SPECT له فحوصات كثيرة، كل منها يستخدم نظيراً مختلفاً. الأكثر شيوعاً: '
      'العظام، القلب، الكلى، والغدة الدرقية. الفحص قد يستغرق 30-60 دقيقة.',
  procedures: [
    Procedure(
      id: 'bone_scan',
      icon: '🦴',
      nameEn: 'Bone Scan',
      nameAr: 'مسح العظام',
      shortDesc:
          'الأكثر استخداماً في الطب النووي. Tc-99m-MDP يتراكم في العظام.',
      type: ProcedureType.diagnostic,
      duration: '60-90 دقيقة',
      preparation: 'شرب ماء',
      contrast: 'Tc-99m-MDP وريدي',
      doseLevel: 'متوسطة (5 mSv)',
      indications: [
        'نقائل عظمية',
        'كسور إجهادية',
        'التهاب العظم',
        'أورام عظمية',
        'ألم عظمي مجهول',
      ],
      preparationSteps: [
        'شرب 1-2 لتر ماء',
        'حقن Tc-99m-MDP',
        'انتظار 3-4 ساعات',
        'تفريغ المثانة قبل التصوير',
        'تصوير أمامي وخلفي',
      ],
      notes: 'يُكشف النقائل قبل ظهورها في X-ray بـ 3-6 أشهر.',
    ),
    Procedure(
      id: 'myocardial_perfusion',
      icon: '❤️',
      nameEn: 'Myocardial Perfusion (SPECT)',
      nameAr: 'تروية عضلة القلب',
      shortDesc:
          'الأكثر استخداماً للقلب. يُقيّم تروية القلب مع إجهاد.',
      type: ProcedureType.functional,
      duration: '3-4 ساعات',
      preparation: 'صيام 4 ساعات',
      contrast: 'Tc-99m-Sestamibi وريدي',
      doseLevel: 'متوسطة',
      indications: [
        'نقص تروية القلب',
        'ألم صدري غير نموذجي',
        'تقييم قبل الجراحة',
        'متابعة بعد الدعامات',
      ],
      preparationSteps: [
        'صيام 4 ساعات',
        'إيقاف الكافيين 24 ساعة',
        'إيقاف Beta-blockers (حسب الطبيب)',
        'تصوير Stress + Rest',
      ],
      notes: 'يُظهر المناطق التي تعاني نقص تروية عند الإجهاد.',
    ),
    Procedure(
      id: 'thyroid_scan',
      icon: '🦋',
      nameEn: 'Thyroid Scan',
      nameAr: 'مسح الغدة الدرقية',
      shortDesc:
          'تقييم وظيفة الغدة الدرقية. Tc-99m أو I-123.',
      type: ProcedureType.diagnostic,
      duration: '30 دقيقة',
      preparation: 'إيقاف أدوية الغدة',
      contrast: 'Tc-99m أو I-123',
      doseLevel: 'منخفضة (2 mSv)',
      indications: [
        'فرط نشاط الغدة',
        'عقد درقية',
        'تقييم بعد استئصال',
        'متابعة سرطان الغدة',
      ],
      preparationSteps: [
        'إيقاف أدوية الغدة 4-6 أسابيع',
        'إيقاف اليود 4 أسابيع',
        'حقن Tc-99m',
        'انتظار 20 دقيقة',
        'تصوير الرقبة',
      ],
      notes: 'يُميز بين Graves و Toxic Nodule.',
    ),
    Procedure(
      id: 'renal_scan',
      icon: '🫘',
      nameEn: 'Renal Scan (DTPA/MAG3)',
      nameAr: 'مسح الكلى',
      shortDesc:
          'تقييم وظيفة الكلى، التروية، والانسداد.',
      type: ProcedureType.functional,
      duration: '45-60 دقيقة',
      preparation: 'شرب ماء',
      contrast: 'Tc-99m-DTPA أو MAG3',
      doseLevel: 'متوسطة',
      indications: [
        'انسداد بولي',
        'وظيفة الكلى',
        'متابعة زرع الكلى',
        'ارتداد بولي',
        'ضغط الدم الكلوي',
      ],
      preparationSteps: [
        'شرب ماء قبل الفحص',
        'تفريغ المثانة',
        'حقن النظير',
        'تصوير ديناميكي متكرر',
      ],
      notes: 'يُعطي منحنى وظيفي لكل كلية.',
    ),
    Procedure(
      id: 'vq_scan',
      icon: '🫁',
      nameEn: 'V/Q Scan (Lung)',
      nameAr: 'مسح الرئة V/Q',
      shortDesc:
          'للجلطة الرئوية. يُقارن التهوية مع التروية.',
      type: ProcedureType.diagnostic,
      duration: '45 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'Tc-99m-MAA + Xenon',
      doseLevel: 'منخفضة',
      indications: [
        'جلطة رئوية',
        'ارتفاع ضغط رئوي',
        'تقييم قبل جراحة الرئة',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'تصوير التهوية (Xenon)',
        'تصوير التروية (MAA)',
        'مقارنة الصورتين',
      ],
      notes: 'يُستخدم عند تعارض CTPA (فشل كلوي، حساسية).',
    ),
    Procedure(
      id: 'sentinel_node',
      icon: '🎗️',
      nameEn: 'Sentinel Node (Lymphoscintigraphy)',
      nameAr: 'العقدة اللمفية الحارسة',
      shortDesc:
          'تحديد أول عقدة لمفية تستقبل الورم — للسرطان.',
      type: ProcedureType.diagnostic,
      duration: '60-90 دقيقة',
      preparation: 'حسب الحالة',
      contrast: 'Tc-99m-Sulfur Colloid',
      doseLevel: 'منخفضة',
      indications: [
        'سرطان الثدي',
        'سرطان الجلد (ميلانوما)',
        'سرطان البروستاتا',
        'سرطان الرحم',
      ],
      preparationSteps: [
        'حقن حول الورم',
        'تصوير لمدة 30-60 دقيقة',
        'وضع علامة على الجلد',
        'الجراح يزيل العقدة الحارسة',
      ],
      notes: 'يُقلل الحاجة لاستئصال كل العقد اللمفية.',
    ),
    Procedure(
      id: 'gi_bleeding',
      icon: '🩸',
      nameEn: 'GI Bleeding Scan',
      nameAr: 'مسح النزيف الهضمي',
      shortDesc:
          'كشف نزيف هضمي غير مرئي بالمنظار.',
      type: ProcedureType.diagnostic,
      duration: '60 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'Tc-99m-RBC',
      doseLevel: 'متوسطة',
      indications: [
        'نزيف هضمي غير معروف',
        'نزيف متكرر',
        'تقييم قبل القسطرة',
      ],
      preparationSteps: [
        'بدون تحضير',
        'حقن كريات موسومة',
        'تصوير متكرر',
      ],
      notes: 'يُحدد موقع النزيف إذا كان > 0.1 mL/min.',
    ),
    Procedure(
      id: 'brain_spect',
      icon: '🧠',
      nameEn: 'Brain SPECT',
      nameAr: 'SPECT الدماغ',
      shortDesc:
          'تقييم تدفق الدم الدماغي. الموت الدماغي، الصرع.',
      type: ProcedureType.functional,
      duration: '45 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'Tc-99m-HMPAO',
      doseLevel: 'متوسطة',
      indications: [
        'الموت الدماغي',
        'الصرع',
        'الخرف',
        'إصابات الدماغ',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'حقن النظير',
        'تصوير الدماغ',
      ],
      notes: 'يُعطي صورة وظيفية للدماغ — تكمّل CT/MRI.',
    ),
    Procedure(
      id: 'liver_scan',
      icon: '🩻',
      nameEn: 'Liver/Spleen Scan',
      nameAr: 'مسح الكبد والطحال',
      shortDesc:
          'تقييم الكبد والطحال — الأورام، الكيسات، الانسداد.',
      type: ProcedureType.diagnostic,
      duration: '60 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'Tc-99m-Sulfur Colloid',
      doseLevel: 'متوسطة',
      indications: [
        'أورام الكبد',
        'أورام الطحال',
        'تشمع الكبد',
        'تقييم بعد استئصال',
      ],
      preparationSteps: [
        'بدون تحضير',
        'حقن النظير',
        'انتظار 15-30 دقيقة',
        'تصوير متعدد الزوايا',
      ],
      notes: 'يُظهر الأنسجة الوظيفية فقط (Kupffer cells).',
    ),
    Procedure(
      id: 'gallium_scan',
      icon: '🔥',
      nameEn: 'Gallium Scan',
      nameAr: 'مسح الغاليوم',
      shortDesc:
          'كشف الالتهابات والأورام بـ Ga-67.',
      type: ProcedureType.diagnostic,
      duration: '3-4 أيام',
      preparation: 'حسب الحالة',
      contrast: 'Ga-67 وريدي',
      doseLevel: 'عالية (10-15 mSv)',
      indications: [
        'الالتهابات المزمنة',
        'اللِمفومة',
        'الساركويد',
        'الحمى مجهولة المنشأ',
      ],
      preparationSteps: [
        'حقن Ga-67',
        'تصوير بعد 24-72 ساعة',
        'شرب ماء كثير',
        'حقنة شرجية قبل التصوير',
      ],
      notes: 'قد يحتاج أياماً — بطيء لكن حساس.',
    ),
    Procedure(
      id: 'octreotide_scan',
      icon: '🧬',
      nameEn: 'Octreotide Scan',
      nameAr: 'مسح الأوكتريوتيد',
      shortDesc:
          'للأورام العصبية الصمّاء بـ In-111 Octreotide.',
      type: ProcedureType.diagnostic,
      duration: '2-3 أيام',
      preparation: 'حسب الحالة',
      contrast: 'In-111 Octreotide',
      doseLevel: 'عالية',
      indications: [
        'الأورام العصبية الصمّاء (NETs)',
        'الورم السرطاوي (Carcinoid)',
        'الورم الغاستريني',
      ],
      preparationSteps: [
        'حقن النظير',
        'تصوير بعد 4 ساعات',
        'ثم بعد 24 ساعة',
        'ثم بعد 48 ساعة',
      ],
      notes: 'يُستخدم قبل PET DOTATATE بكثير، لا يزال مفيداً.',
    ),
    Procedure(
      id: 'spect_ct',
      icon: '🔗',
      nameEn: 'SPECT/CT Hybrid',
      nameAr: 'SPECT/CT المدمج',
      shortDesc:
          'دمج SPECT مع CT لتشريح دقيق + وظيفة. الأكثر دقة.',
      type: ProcedureType.diagnostic,
      duration: '45-60 دقيقة',
      preparation: 'حسب الفحص',
      contrast: 'حسب الفحص',
      doseLevel: 'متوسطة-عالية',
      indications: [
        'نقائل عظمية (بدقة أعلى)',
        'العدوى',
        'سرطان الغدة الدرقية',
        'القلب',
      ],
      preparationSteps: [
        'حسب نوع SPECT',
        'تصوير SPECT ثم CT',
        'دمج الصور تلقائياً',
      ],
      notes: 'الأكثر حساسية ودقة في الطب النووي الحديث.',
    ),
  ],
  comparisonHeaders: ['الفحص', 'النظير', 'المدة', 'الأفضل لـ'],
  comparisonTable: [
    ['عظام', 'Tc-99m-MDP', '60-90 دقيقة', 'النقائل العظمية'],
    ['قلب', 'Tc-99m-Sestamibi', '3-4 ساعات', 'نقص التروية'],
    ['غدة درقية', 'Tc-99m', '30 دقيقة', 'فرط النشاط'],
    ['كلى', 'Tc-99m-DTPA/MAG3', '45-60 دقيقة', 'وظائف الكلى'],
    ['V/Q رئة', 'Tc-99m-MAA', '45 دقيقة', 'الجلطة الرئوية'],
    ['عقدة حارسة', 'Tc-99m-Sulfur', '60-90 دقيقة', 'السرطان'],
    ['نزيف هضمي', 'Tc-99m-RBC', '60 دقيقة', 'نزيف مجهول'],
    ['دماغ', 'Tc-99m-HMPAO', '45 دقيقة', 'الموت الدماغي'],
    ['كبد/طحال', 'Tc-99m-Sulfur', '60 دقيقة', 'أورام الكبد'],
    ['غاليوم', 'Ga-67', '3-4 أيام', 'الالتهابات'],
    ['SPECT/CT', 'مختلف', '45-60 دقيقة', 'الدقة الأعلى'],
  ],
);