import '../procedure_model.dart';

const ProceduresData ultrasoundProcedures = ProceduresData(
  deviceId: 'us',
  intro:
      'Ultrasound له أنواع كثيرة، كل منها يحتاج مسبار مختلف. من الفحوصات '
      'البسيطة (10 دقائق) إلى المتقدمة (60 دقيقة). كلها آمنة تماماً.',
  procedures: [
    Procedure(
      id: 'us_abdominal',
      icon: '🩻',
      nameEn: 'Abdominal Ultrasound',
      nameAr: 'Ultrasound بطن',
      shortDesc:
          'فحص شامل للبطن — الكبد، المرارة، البنكرياس، الكلى، الطحال.',
      type: ProcedureType.diagnostic,
      duration: '15-20 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'ألم بطني',
        'حصى المرارة',
        'تضخم الكبد',
        'تقييم الكلى',
        'استسقاء بطني',
      ],
      preparationSteps: [
        'صيام 6-8 ساعات',
        'شرب ماء قليل',
        'رفع الملابس',
        'الاستلقاء على الظهر',
      ],
      notes: 'الصيام ضروري — الغازات تحجب الرؤية.',
    ),
    Procedure(
      id: 'us_pelvic',
      icon: '🤰',
      nameEn: 'Pelvic Ultrasound',
      nameAr: 'Ultrasound الحوض',
      shortDesc:
          'فحص الحوض — الرحم، المبيض، المثانة. للحمل والنساء.',
      type: ProcedureType.diagnostic,
      duration: '15-30 دقيقة',
      preparation: 'مثانة ممتلئة',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'متابعة الحمل',
        'أورام الرحم والمبيض',
        'نزيف مهبلي',
        'ألم حوضي',
        'تكيسات المبيض',
      ],
      preparationSteps: [
        'شرب 4-6 أكواب ماء قبل ساعة',
        'عدم التبول',
        'الاستلقاء على الظهر',
        'قد يكون Transvaginal للحصول على تفاصيل',
      ],
      notes: 'المثانة الممتلئة تدفع الأمعاء وتُظهر الرحم.',
    ),
    Procedure(
      id: 'us_obstetric',
      icon: '👶',
      nameEn: 'Obstetric Ultrasound',
      nameAr: 'Ultrasound الحمل',
      shortDesc:
          'متابعة الجنين خلال الحمل — القياسات، النبض، التشوهات.',
      type: ProcedureType.diagnostic,
      duration: '20-45 دقيقة',
      preparation: 'حسب مرحلة الحمل',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'تأكيد الحمل',
        'تحديد عمر الجنين',
        'متابعة النمو',
        'كشف التشوهات',
        'تحديد جنس الجنين',
        'تقييم المشيمة',
      ],
      preparationSteps: [
        'حسب بروتوكول المركز',
        'شرب ماء (الثلث الأول)',
        'الاستلقاء على الظهر/الجانب',
      ],
      notes: 'آمن تماماً للجنين. الفحص الدوري في أشهر الحمل ضروري.',
    ),
    Procedure(
      id: 'us_thyroid',
      icon: '🦋',
      nameEn: 'Thyroid Ultrasound',
      nameAr: 'Ultrasound الغدة الدرقية',
      shortDesc:
          'فحص الغدة الدرقية والعقد اللمفية المجاورة.',
      type: ProcedureType.diagnostic,
      duration: '10-15 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'عقد درقية',
        'تضخم الغدة',
        'فرط أو نقص نشاط',
        'متابعة سرطان الغدة',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'رفع الرأس قليلاً',
        'كشف الرقبة',
      ],
      notes: 'يُدمج عادة مع Fine Needle Aspiration (FNA) للعقد المشبوهة.',
    ),
    Procedure(
      id: 'us_breast',
      icon: '🎗️',
      nameEn: 'Breast Ultrasound',
      nameAr: 'Ultrasound الثدي',
      shortDesc:
          'فحص الثدي بالـ Ultrasound — مكمل لـ Mammography.',
      type: ProcedureType.diagnostic,
      duration: '15-30 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'كتلة محسوسة',
        'الثدي الكثيف (Mammography غير كافية)',
        'متابعة كيس',
        'توجيه الخزعة',
        'الحمل والرضاعة',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'رفع الذراع فوق الرأس',
        'الاستلقاء على الظهر',
      ],
      notes: 'يُستخدم مع Mammography للتشخيص المزدوج.',
    ),
    Procedure(
      id: 'echo',
      icon: '❤️',
      nameEn: 'Echocardiography',
      nameAr: 'إيكو القلب',
      shortDesc:
          'Ultrasound القلب — يُقيّم العضلة، الصمامات، والوظيفة.',
      type: ProcedureType.diagnostic,
      duration: '30-45 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'فشل قلبي',
        'أمراض الصمامات',
        'اعتلال عضلة القلب',
        'التهاب التامور',
        'عيوب خلقية',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'كشف الصدر',
        'الاستلقاء على الجانب الأيسر',
        'مراقبة ECG (قد يُطلب)',
      ],
      notes: 'TEE (عبر المريء) لتفاصيل أدق — يحتاج تخديراً موضعياً.',
    ),
    Procedure(
      id: 'doppler_vascular',
      icon: '🩸',
      nameEn: 'Vascular Doppler',
      nameAr: 'دوبلر الأوعية',
      shortDesc:
          'قياس تدفق الدم في الشرايين والأوردة. يكشف الجلطات والتضيّقات.',
      type: ProcedureType.functional,
      duration: '30-60 دقيقة',
      preparation: 'حسب المنطقة',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'جلطة وريدية عميقة (DVT)',
        'تضيّق الشريان السباتي',
        'تضيّق الشرايين الطرفية',
        'الدوالي الوريدية',
        'متابعة بعد الجراحة',
      ],
      preparationSteps: [
        'بدون تحضير عام',
        'ملابس فضفاضة',
        'كشف المنطقة',
        'قد يحتاج وضعية معينة',
      ],
      notes: 'الزاوية < 60° ضرورية لقياس دقيق.',
    ),
    Procedure(
      id: 'fast_scan',
      icon: '🚑',
      nameEn: 'FAST Scan',
      nameAr: 'فحص FAST للطوارئ',
      shortDesc:
          'Focused Assessment with Sonography for Trauma — للطوارئ.',
      type: ProcedureType.diagnostic,
      duration: '5 دقائق',
      preparation: 'لا وقت للتحضير',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'إصابات البطن الحادة',
        'نزيف داخلي مشتبه',
        'استرواح الصدر',
        'إصابات متعددة',
      ],
      preparationSteps: [
        'لا تحضير — طوارئ',
        '4 نوافذ قياسية',
        'سريع جداً (2-5 دقائق)',
      ],
      notes: 'يُنقذ الأرواح — يكشف النزيف الداخلي في ثوانٍ.',
    ),
    Procedure(
      id: 'us_kidney',
      icon: '🫘',
      nameEn: 'Renal Ultrasound',
      nameAr: 'Ultrasound الكلى',
      shortDesc:
          'فحص الكلى والمثانة — للحصى والانسداد والوظيفة.',
      type: ProcedureType.diagnostic,
      duration: '15-20 دقيقة',
      preparation: 'مثانة ممتلئة',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'حصى الكلى',
        'انسداد بولي',
        'التهاب كلى',
        'فشل كلوي',
        'متابعة بعد الزرع',
      ],
      preparationSteps: [
        'شرب ماء قبل ساعة',
        'عدم التبول',
        'وضعية جانبية وكلى',
      ],
      notes: 'قد لا يكشف الحصى الصغيرة (< 3 mm) — CT أدق.',
    ),
    Procedure(
      id: 'us_guided',
      icon: '💉',
      nameEn: 'Ultrasound-Guided Procedures',
      nameAr: 'إجراءات موجهة بالـ Ultrasound',
      shortDesc:
          'خزعة، تصريف خراج، قسطرة، تثبيت — بمساعدة Ultrasound الحية.',
      type: ProcedureType.interventional,
      duration: '30-60 دقيقة',
      preparation: 'صيام 6 ساعات',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'خزعة من الأعضاء',
        'تصريف خراج',
        'تركيب قسطرة مركزية',
        'تصريف الكيس',
        'حقن موضعي',
      ],
      preparationSteps: [
        'صيام 6 ساعات',
        'تحاليل التخثر',
        'توقيع موافقة',
        'تخدير موضعي',
        'مراقبة بعد الإجراء',
      ],
      notes: 'Ultrasound يُفضّل على CT للتوجيه — بدون إشعاع وحية.',
    ),
    Procedure(
      id: 'transvaginal',
      icon: '🧭',
      nameEn: 'Transvaginal Ultrasound',
      nameAr: 'Ultrasound مهبلي',
      shortDesc:
          'Ultrasound داخل المهبل — تفاصيل أدق للرحم والمبيض.',
      type: ProcedureType.diagnostic,
      duration: '15-20 دقيقة',
      preparation: 'مثانة فارغة',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'متابعة الحمل المبكر',
        'تكيسات المبيض',
        'أورام الرحم',
        'نزيف غير طبيعي',
        'العقم',
      ],
      preparationSteps: [
        'تفريغ المثانة',
        'وضعية Lithotomy',
        'تغطية المسبار بغلاف معقم',
        'تغطية المريضة',
      ],
      notes: 'أدق من Ultrasound الحوض العادي — لكن قد يكون غير مريح.',
    ),
    Procedure(
      id: 'tcd',
      icon: '🧠',
      nameEn: 'Transcranial Doppler (TCD)',
      nameAr: 'دوبلر عبر الجمجمة',
      shortDesc:
          'قياس تدفق الدم في الشرايين الدماغية عبر عظم الجمجمة.',
      type: ProcedureType.functional,
      duration: '30-60 دقيقة',
      preparation: 'بدون تحضير',
      contrast: 'بدون',
      doseLevel: 'صفر',
      indications: [
        'جلطة دماغية',
        'تضيّق الشرايين الدماغية',
        'الصداع النصفي',
        'الانيميا المنجلية (أطفال)',
        'الموت الدماغي',
      ],
      preparationSteps: [
        'بدون تحضير خاص',
        'المريض مستلقياً',
        'المسبار على الصدغ',
      ],
      notes: 'يحتاج مسبار منخفض التردد (2 MHz) لاختراق العظم.',
    ),
  ],
  comparisonHeaders: ['الفحص', 'المدة', 'التحضير', 'الأفضل لـ'],
  comparisonTable: [
    ['بطن', '15-20 دقيقة', 'صيام 6 ساعات', 'الكبد والمرارة'],
    ['حوض', '15-30 دقيقة', 'مثانة ممتلئة', 'الرحم والمبيض'],
    ['حمل', '20-45 دقيقة', 'مثانة ممتلئة', 'متابعة الجنين'],
    ['غدة درقية', '10-15 دقيقة', 'بدون', 'عقد الغدة'],
    ['ثدي', '15-30 دقيقة', 'بدون', 'كتل الثدي'],
    ['إيكو قلب', '30-45 دقيقة', 'بدون', 'الصمامات والعضلة'],
    ['دوبلر أوعية', '30-60 دقيقة', 'حسب المنطقة', 'الجلطات'],
    ['FAST', '5 دقائق', 'لا وقت', 'الطوارئ'],
    ['كلى', '15-20 دقيقة', 'مثانة ممتلئة', 'حصى الكلى'],
    ['إجراءات موجهة', '30-60 دقيقة', 'صيام 6 ساعات', 'خزعة، تصريف'],
    ['مهبلي', '15-20 دقيقة', 'مثانة فارغة', 'الحمل المبكر'],
    ['TCD', '30-60 دقيقة', 'بدون', 'شرايين الدماغ'],
  ],
);