import '../procedure_model.dart';

const ProceduresData xrayProcedures = ProceduresData(
  deviceId: 'xray',
  intro:
      'الأشعة السينية العادية لها عشرات الفحوصات حسب المنطقة. كل فحص له '
      'بروتوكول خاص من حيث الوضعية والعوامل. نذكر هنا الأكثر استخداماً.',
  procedures: [
    Procedure(
      id: 'chest_pa',
      icon: '🫁',
      nameEn: 'Chest X-ray (PA + Lateral)',
      nameAr: 'أشعة صدر',
      shortDesc:
          'أشهر فحص بالأشعة السينية. يُظهر الرئة، القلب، الأضلاع، والحجاب الحاجز.',
      type: ProcedureType.diagnostic,
      duration: '5 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة (0.1 mSv)',
      indications: [
        'التهاب رئوي، سل، كوفيد',
        'استرواح صدر، انصباب جنبي',
        'تضخم قلب، فشل قلبي',
        'أورام رئوية',
        'كسور أضلاع',
        'فحص روتيني قبل العمليات',
      ],
      preparationSteps: [
        'خلع الملابس العلوية ولبس رداء المستشفى',
        'إزالة السلاسل والمجوهرات',
        'الوقوف أمام الكاشف، الصدر ملتصق',
        'الذراعان خلف الظهر لدفع الكتفين للأمام',
        'حبس النفس عند الطلب',
      ],
      notes: 'صورة PA هي الأساس. صورة Lateral تُظهر الأضلاع والقلب بعمق.',
    ),
    Procedure(
      id: 'abdominal',
      icon: '🩻',
      nameEn: 'Abdominal X-ray (KUB)',
      nameAr: 'أشعة بطن / KUB',
      shortDesc:
          'أشعة للبطن تُظهر الكلى، الحالب، المثانة، والأمعاء. شائعة لحصى الكلى.',
      type: ProcedureType.diagnostic,
      duration: '5-10 دقائق',
      preparation: 'بدون صيام عادة',
      contrast: 'بدون',
      doseLevel: 'منخفضة (1 mSv)',
      indications: [
        'حصى الكلى والحالب (KUB)',
        'انسداد معوي',
        'أجسام غريبة',
        'غازات حرة (ثقب)',
        'تقييم أنبوب التغذية أو القسطرة',
      ],
      preparationSteps: [
        'إزالة الأحزمة والأزرار المعدنية',
        'الاستلقاء على الظهر',
        'الذراعان بجانب الجسم أو فوق الرأس',
        'حبس النفس إذا أمكن',
      ],
      notes: 'KUB اسمه من Kidney-Ureter-Bladder. قد لا يرى كل الحصى — CT أكثر حساسية.',
    ),
    Procedure(
      id: 'skull',
      icon: '💀',
      nameEn: 'Skull X-ray',
      nameAr: 'أشعة جمجمة',
      shortDesc:
          'أشعة للجمجمة. أقل استخداماً بعد ظهور CT، لكن مفيدة في بعض الحالات.',
      type: ProcedureType.diagnostic,
      duration: '10 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة (0.2 mSv)',
      indications: [
        'كسور جمجمة بسيطة',
        'أجسام غريبة في الأنف/الأذن',
        'تشوهات عظمية',
        'تقييم الجيوب (Caldwell, Waters)',
      ],
      preparationSteps: [
        'إزالة الأقراط، السلاسل، دبابيس الشعر',
        'الجلوس أو الاستلقاء',
        'وضعيات متعددة (AP, Lateral, Towne)',
        'البقاء ساكناً تماماً',
      ],
      notes: 'CT هو الأفضل لإصابات الرأس الحادة. X-ray للكسور البسيطة فقط.',
    ),
    Procedure(
      id: 'spine',
      icon: '🦴',
      nameEn: 'Spine X-ray',
      nameAr: 'أشعة العمود الفقري',
      shortDesc:
          'أشعة للعمود الفقري (عنقي، صدري، قطني). تُظهر الفقرات والاعوجاج.',
      type: ProcedureType.diagnostic,
      duration: '10-15 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة (1-1.5 mSv)',
      indications: [
        'كسور فقرية',
        'انحناء العمود (Scoliosis)',
        'التهاب الفقرات',
        'الفصال العظمي',
        'متابعة زراعة فقرية',
      ],
      preparationSteps: [
        'خلع الملابس العلوية/السفلية حسب المنطقة',
        'إزالة المعادن من المنطقة',
        'الوقوف أو الاستلقاء حسب المنطقة',
        'وضعيات AP + Lateral',
      ],
      notes: 'MRI أفضل للأنسجة الرخوة (الغضاريف، الأعصاب). X-ray للعظام فقط.',
    ),
    Procedure(
      id: 'extremities',
      icon: '🦵',
      nameEn: 'Extremities X-ray',
      nameAr: 'أشعة الأطراف',
      shortDesc:
          'أشعة لليد، الرسغ، المرفق، الكتف، القدم، الكاحل، الركبة، الفخذ.',
      type: ProcedureType.diagnostic,
      duration: '5-10 دقائق',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة جداً (< 0.1 mSv)',
      indications: [
        'كسور، خلع',
        'التهاب المفاصل',
        'هشاشة العظام',
        'أورام عظمية',
        'أجسام غريبة',
      ],
      preparationSteps: [
        'خلع المجوهرات والساعات',
        'وضع الطرف على الكاشف',
        'وضعيات متعددة (AP, Lateral, Oblique)',
        'البقاء ساكناً تماماً',
      ],
      notes: 'عادة صورتان على الأقل لكل طرف (AP + Lateral).',
    ),
    Procedure(
      id: 'dental',
      icon: '🦷',
      nameEn: 'Dental X-ray',
      nameAr: 'أشعة الأسنان',
      shortDesc:
          'أشعة للأسنان والفك. أنواع: Periapical، Bitewing، Panoramic.',
      type: ProcedureType.diagnostic,
      duration: '5-15 دقيقة',
      preparation: 'بدون صيام',
      contrast: 'بدون',
      doseLevel: 'منخفضة جداً (0.005 mSv)',
      indications: [
        'تسوس الأسنان',
        'خراجات، أكياس',
        'كسور الأسنان',
        'قبل زراعة الأسنان',
        'تقييم جذور الأسنان',
      ],
      preparationSteps: [
        'إزالة أي معدن من الرأس (أقراط، دبابيس)',
        'وضع واقي الرصاص على الصدر',
        'عضّ الفيلم أو المستشعر',
        'البقاء ساكناً',
      ],
      notes: 'Panoramic يعطي صورة شاملة للفك كاملاً في صورة واحدة.',
    ),
    Procedure(
      id: 'mammo_xray',
      icon: '🩻',
      nameEn: 'Mammography',
      nameAr: 'تصوير الثدي',
      shortDesc:
          'تصوير متخصص للثدي بأشعة سينية منخفضة الطاقة. للكشف المبكر عن السرطان.',
      type: ProcedureType.diagnostic,
      duration: '20 دقيقة',
      preparation: 'بدون مزيل عرق',
      contrast: 'بدون (عادة)',
      doseLevel: 'منخفضة (0.4 mSv)',
      indications: [
        'الفحص الدوري للنساء 40+',
        'كتلة محسوسة',
        'إفرازات حلمة',
        'تاريخ عائلي لسرطان الثدي',
      ],
      preparationSteps: [
        'لا مزيل عرق أو كريم أو بودرة',
        'لبس ملابس من قطعة واحدة',
        'إحضار الصور السابقة',
        'الوقوف أمام الجهاز',
      ],
      notes: 'التوقيت الأفضل: بعد الدورة بأسبوع. الفحص الدوري يُنقذ الأرواح.',
    ),
    Procedure(
      id: 'fluoroscopy',
      icon: '📺',
      nameEn: 'Fluoroscopy',
      nameAr: 'التنظير التألقي',
      shortDesc:
          'أشعة حية (Real-time) لمتابعة الحركة داخل الجسم. يشمل بلع الباريوم، الحقنة الشرجية.',
      type: ProcedureType.diagnostic,
      duration: '15-30 دقيقة',
      preparation: 'صيام 6-8 ساعات',
      contrast: 'فموي/شرجي (باريوم)',
      doseLevel: 'متوسطة (2-5 mSv)',
      indications: [
        'دراسة البلع والمريء',
        'تشخيص الارتجاع',
        'انسداد معوي',
        'دراسة حركة الأمعاء',
      ],
      preparationSteps: [
        'صيام 6-8 ساعات',
        'عدم التدخين قبل الفحص',
        'لبس رداء المستشفى',
        'شرب الباريوم أو الحقنة الشرجية',
      ],
      notes: 'لا يُستخدم الباريوم في حالات الانسداد الكامل — يُستخدم تباين يودي.',
    ),
    Procedure(
      id: 'portable',
      icon: '🚑',
      nameEn: 'Portable X-ray',
      nameAr: 'أشعة محمولة',
      shortDesc:
          'جهاز X-ray محمول يُنقل إلى سرير المريض. للحالات الحرجة في العناية المركزة.',
      type: ProcedureType.diagnostic,
      duration: '5-10 دقائق',
      preparation: 'حسب الحالة',
      contrast: 'بدون',
      doseLevel: 'منخفضة-متوسطة',
      indications: [
        'مرضى العناية المركزة',
        'مرضى غير قادرين على الحركة',
        'متابعة أنابيب الصدر',
        'طوارئ الحوادث',
      ],
      preparationSteps: [
        'ارتدِ المئزر الرصاصي',
        'ضع الكاشف خلف المريض',
        'تأكد من عدم وجود معدن في المسار',
        'حماية المحيطين (Stand Behind)',
      ],
      notes: 'الجرعة قد تكون أعلى بسبب عدم استخدام الكوليماتور المثالي.',
    ),
  ],
  comparisonHeaders: ['الفحص', 'المدة', 'الجرعة', 'الأفضل لـ'],
  comparisonTable: [
    ['صدر', '5 دقائق', '0.1 mSv', 'الرئة والقلب'],
    ['بطن KUB', '5-10 دقائق', '1 mSv', 'حصى الكلى'],
    ['جمجمة', '10 دقائق', '0.2 mSv', 'كسور بسيطة'],
    ['عمود فقري', '10-15 دقيقة', '1-1.5 mSv', 'الكسور والاعوجاج'],
    ['أطراف', '5-10 دقائق', '< 0.1 mSv', 'الكسور والالتهابات'],
    ['أسنان', '5-15 دقيقة', '0.005 mSv', 'التسوس والخراجات'],
    ['ثدي', '20 دقيقة', '0.4 mSv', 'سرطان الثدي'],
    ['تنظير تألقي', '15-30 دقيقة', '2-5 mSv', 'الجهاز الهضمي'],
    ['محمول', '5-10 دقائق', 'منخفضة-متوسطة', 'الطوارئ والعناية'],
  ],
);